CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE titles (id text PRIMARY KEY, media_type text NOT NULL CHECK(media_type IN ('movie','tv')), tmdb_id bigint NOT NULL CHECK(tmdb_id>0), data jsonb NOT NULL, revision text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(media_type,tmdb_id));
CREATE TABLE localizations (title_id text REFERENCES titles ON DELETE CASCADE, locale text NOT NULL CHECK(locale IN ('de','fr','it','es','en')), title text NOT NULL, overview text NOT NULL DEFAULT '', slug text NOT NULL, source text NOT NULL, source_hash text NOT NULL, search_document tsvector GENERATED ALWAYS AS (to_tsvector('simple',title)) STORED, PRIMARY KEY(title_id,locale), UNIQUE(locale,slug,title_id));
CREATE INDEX localization_search ON localizations USING gin(search_document);
CREATE INDEX title_updated ON titles(updated_at DESC);
CREATE TABLE slug_history (title_id text REFERENCES titles ON DELETE CASCADE, locale text NOT NULL, slug text NOT NULL, PRIMARY KEY(title_id,locale,slug));
CREATE TABLE seasons (title_id text REFERENCES titles ON DELETE CASCADE, number int NOT NULL, data jsonb NOT NULL, PRIMARY KEY(title_id,number));
CREATE TABLE episodes (title_id text, season int, number int NOT NULL, data jsonb NOT NULL, PRIMARY KEY(title_id,season,number), FOREIGN KEY(title_id,season) REFERENCES seasons(title_id,number) ON DELETE CASCADE);
CREATE TABLE markets (code text PRIMARY KEY CHECK(code ~ '^[a-z]{2}$'), verified_at timestamptz, supported boolean NOT NULL DEFAULT false);
CREATE TABLE providers (market text REFERENCES markets, id text NOT NULL, data jsonb NOT NULL, PRIMARY KEY(market,id));
CREATE TABLE snapshots (title_id text REFERENCES titles ON DELETE CASCADE, market text REFERENCES markets, availability text NOT NULL CHECK(availability IN ('available','empty','unsupported','unchecked','error')), checked_at timestamptz, attempt_at timestamptz, error_code text, revision bigint NOT NULL DEFAULT 0, PRIMARY KEY(title_id,market));
CREATE TABLE offers (id text PRIMARY KEY, title_id text NOT NULL, market text NOT NULL, provider_id text NOT NULL, data jsonb NOT NULL, expires_at timestamptz, FOREIGN KEY(title_id,market) REFERENCES snapshots ON DELETE CASCADE, FOREIGN KEY(market,provider_id) REFERENCES providers(market,id));
CREATE INDEX offers_scope ON offers(market,title_id);
CREATE INDEX offers_expiry ON offers(expires_at) WHERE expires_at IS NOT NULL;
CREATE TABLE changes (id text PRIMARY KEY, title_id text REFERENCES titles ON DELETE CASCADE, market text REFERENCES markets, kind text NOT NULL, provider text NOT NULL, at timestamptz NOT NULL DEFAULT now());
CREATE INDEX changes_title ON changes(title_id,market,at DESC);
CREATE TABLE jobs (id bigserial PRIMARY KEY, key text UNIQUE NOT NULL, kind text NOT NULL, payload jsonb NOT NULL, state text NOT NULL DEFAULT 'queued' CHECK(state IN ('queued','running','done','dead','paused')), attempts int NOT NULL DEFAULT 0, run_at timestamptz NOT NULL DEFAULT now(), lock_until timestamptz, lock_token text, heartbeat timestamptz, error_code text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX runnable_jobs ON jobs(run_at) WHERE state IN ('queued','running');
CREATE TABLE sync_runs (id text PRIMARY KEY, scope text NOT NULL, completed boolean NOT NULL DEFAULT false, cursor text, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE watermarks (scope text PRIMARY KEY, timestamp bigint NOT NULL);
CREATE TABLE budgets (service text NOT NULL, period text NOT NULL, consumed bigint NOT NULL DEFAULT 0, PRIMARY KEY(service,period));
CREATE TABLE budget_reservations (id bigserial PRIMARY KEY, service text NOT NULL, units int NOT NULL, at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reports (id bigserial PRIMARY KEY, locale text NOT NULL, market text NOT NULL, title_id text, message text NOT NULL CHECK(length(message) BETWEEN 10 AND 3000), email text, resolved boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE rate_limits (key text PRIMARY KEY, count int NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE operations (key text PRIMARY KEY, data jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events (id bigserial PRIMARY KEY, event text NOT NULL, subject text, at timestamptz NOT NULL DEFAULT now());
CREATE TABLE quarantines (id bigserial PRIMARY KEY, scope text NOT NULL, reason text NOT NULL, data jsonb NOT NULL, at timestamptz NOT NULL DEFAULT now());
CREATE TABLE editorial (slug text PRIMARY KEY, versions jsonb NOT NULL, author text NOT NULL, revision text NOT NULL, published boolean NOT NULL DEFAULT false CHECK(NOT published OR versions ?& ARRAY['de','fr','it','es','en']));
