import type { Locale } from '../../i18n/config';
export type Localized = Record<Locale, string>;
export const l = (
  de: string,
  fr: string,
  it: string,
  es: string,
  en: string,
): Localized => ({ de, fr, it, es, en });
export const copy = {
  breadcrumb: l(
    'Brotkrumennavigation',
    'Fil d’Ariane',
    'Percorso di navigazione',
    'Ruta de navegación',
    'Breadcrumb',
  ),
  hub: l(
    'Streaming-Guides im Vergleich',
    'Comparatif des guides de streaming',
    'Guide streaming a confronto',
    'Comparativa de guías de streaming',
    'Streaming guides compared',
  ),
  hubIntro: l(
    'Den richtigen Film finden ist eine Aufgabe. Das passende Angebot, eine gemeinsame Liste oder die nächste ungesehene Episode eine andere. Vergleiche zehn Dienste nach dem, was du wirklich brauchst.',
    'Trouver le bon film, une offre de streaming, une liste partagée ou le prochain épisode : ce sont des besoins différents. Comparez dix services selon votre usage.',
    'Trovare il film giusto, una piattaforma, una lista condivisa o il prossimo episodio sono esigenze diverse. Confronta dieci servizi in base al tuo obiettivo.',
    'Encontrar una película, una oferta, una lista compartida o el siguiente episodio son necesidades distintas. Compara diez servicios según lo que buscas.',
    'Finding a film, a streaming offer, a shared list or your next unwatched episode are different tasks. Compare ten services around what you actually need.',
  ),
  eyebrow: l(
    'Cineradar · Orientierung vor dem Filmabend',
    'Cineradar · Préparez votre soirée',
    'Cineradar · Prima della serata cinema',
    'Cineradar · Antes de tu noche de cine',
    'Cineradar · Before your movie night',
  ),
  versus: l(
    'oder Cineradar?',
    'ou Cineradar ?',
    'o Cineradar?',
    'o Cineradar?',
    'or Cineradar?',
  ),
  alternative: l(
    'Alternative',
    'Alternative',
    'Alternativa',
    'Alternativa',
    'Alternative',
  ),
  compare: l(
    'Funktionen vergleichen',
    'Comparer les fonctions',
    'Confronta le funzioni',
    'Comparar funciones',
    'Compare features',
  ),
  overview: l(
    'Die Einordnung',
    'En bref',
    'Il contesto',
    'El contexto',
    'The context',
  ),
  criteria: l(
    'Was zählt für dich?',
    'Votre critère',
    'Cosa conta per te?',
    '¿Qué te importa?',
    'What matters to you?',
  ),
  checked: l(
    'Quellen geprüft',
    'Sources vérifiées',
    'Fonti verificate',
    'Fuentes revisadas',
    'Sources checked',
  ),
  source: l('Quelle', 'Source', 'Fonte', 'Fuente', 'Source'),
  sources: l(
    'Quellen & Methode',
    'Sources et méthode',
    'Fonti e metodo',
    'Fuentes y método',
    'Sources & method',
  ),
  method: l(
    'Herausgeber dieses Vergleichs ist Cineradar, betrieben von Wiresoft AG. Grundlage sind die verlinkten offiziellen Produktbeschreibungen und Cineradars überprüfte Funktionen. Dies ist kein unabhängiger Geschwindigkeitstest. Nicht bestätigte Eigenschaften werden nicht als fehlend gewertet.',
    'Ce comparatif est publié par Cineradar, exploité par Wiresoft AG. Il repose sur les descriptions officielles citées et les fonctions vérifiées de Cineradar. Ce n’est pas un test indépendant de rapidité. Une fonction non confirmée n’est pas considérée comme absente.',
    'Il confronto è pubblicato da Cineradar, gestito da Wiresoft AG. Si basa sulle descrizioni ufficiali citate e sulle funzioni verificate di Cineradar. Non è un test indipendente di velocità. Una funzione non confermata non è considerata assente.',
    'Cineradar, operado por Wiresoft AG, publica esta comparativa a partir de descripciones oficiales y funciones verificadas de Cineradar. No es una prueba independiente de velocidad. Una función no confirmada no se considera inexistente.',
    'This comparison is published by Cineradar, operated by Wiresoft AG. It uses the linked official product descriptions and verified Cineradar features. This is not an independent speed test. Unverified features are not treated as missing.',
  ),
  scope: l(
    'Bezugsmarkt und Plattform stehen bei jeder Aussage. Eine Übersetzung ändert den geprüften Markt nicht.',
    'Le marché et la plateforme sont indiqués pour chaque constat. Traduire la page ne change pas le marché vérifié.',
    'Ogni indicazione specifica mercato e piattaforma. La traduzione non cambia il mercato verificato.',
    'Cada afirmación indica su mercado y plataforma. Traducir no cambia el mercado comprobado.',
    'Each claim states its market and platform. Translating this page does not change the market reviewed.',
  ),
  decision: l(
    'Welche Lösung passt zu dir?',
    'Quel outil vous convient ?',
    'Quale soluzione fa per te?',
    '¿Qué solución te conviene?',
    'Which approach fits you?',
  ),
  workflow: l(
    'Vom Titel zum Streaming-Angebot',
    'Du titre à la plateforme',
    'Dal titolo alla piattaforma',
    'Del título a la plataforma',
    'From title to streaming offer',
  ),
  step1: l(
    'Titel und Land wählen',
    'Choisir le titre et le pays',
    'Scegli titolo e paese',
    'Elige título y país',
    'Choose a title and country',
  ),
  step1Text: l(
    'Gib den Titel ein und prüfe Jahr sowie Film oder Serie. Das Suchland bleibt sichtbar und lässt sich unabhängig von der Sprache ändern.',
    'Saisissez un titre puis vérifiez l’année et le format. Le pays de recherche reste visible et se règle indépendamment de la langue.',
    'Inserisci il titolo e verifica anno e formato. Il paese resta visibile e si sceglie indipendentemente dalla lingua.',
    'Escribe el título y comprueba el año y el formato. El país permanece visible y se cambia independientemente del idioma.',
    'Enter a title and check its year and whether it is a film or show. The search country stays visible and can be changed independently of language.',
  ),
  step2: l(
    'Das passende Angebot prüfen',
    'Vérifier l’offre',
    'Verifica l’offerta',
    'Comprueba la oferta',
    'Check the offer',
  ),
  step2Text: l(
    'Öffne den Treffer. Unterscheide enthaltenes Abo, Zusatzkanal, Leihe und Kauf. Bei Serien prüfst du die Staffel; ein Angebot bedeutet nicht automatisch alle Folgen.',
    'Ouvrez le résultat. Distinguez abonnement, chaîne supplémentaire, location et achat. Pour une série, vérifiez la saison : une offre ne couvre pas forcément tous les épisodes.',
    'Apri il risultato e distingui abbonamento, canale aggiuntivo, noleggio e acquisto. Per le serie verifica la stagione: un’offerta non include sempre tutti gli episodi.',
    'Abre el resultado. Distingue suscripción, canal adicional, alquiler y compra. En las series, comprueba la temporada: una oferta no incluye necesariamente todos los episodios.',
    'Open the result. Distinguish subscription, add-on channel, rental and purchase. For shows, check the season: one offer does not necessarily include every episode.',
  ),
  step3: l(
    'Beim Anbieter ansehen',
    'Regarder sur la plateforme',
    'Guarda sulla piattaforma',
    'Ver en la plataforma',
    'Watch with the provider',
  ),
  step3Text: l(
    'Der Angebotslink führt zum Streamingdienst. Dort gelten dessen Zugang, Preis und Bedingungen. Cineradar spielt keine Filme ab und verkauft keine Abonnements.',
    'Le lien mène au service, où s’appliquent ses conditions d’accès et ses tarifs. Cineradar ne diffuse pas de films et ne vend pas d’abonnements.',
    'Il link apre il servizio con i suoi prezzi e requisiti di accesso. Cineradar non riproduce film e non vende abbonamenti.',
    'El enlace abre el servicio, con sus precios y condiciones. Cineradar no reproduce películas ni vende suscripciones.',
    'The offer link opens the provider, where its access rules, prices and terms apply. Cineradar does not play films or sell subscriptions.',
  ),
  faq: l(
    'Fragen zur Entscheidung',
    'Questions utiles',
    'Domande per scegliere',
    'Preguntas para decidir',
    'Questions to help you decide',
  ),
  next: l(
    'Weiter vergleichen',
    'Poursuivre la comparaison',
    'Altri confronti',
    'Seguir comparando',
    'Keep comparing',
  ),
  searchLabel: l(
    'Welchen Film oder welche Serie suchst du?',
    'Quel film ou quelle série cherchez-vous ?',
    'Quale film o serie cerchi?',
    '¿Qué película o serie buscas?',
    'Which film or show are you looking for?',
  ),
  searchButton: l(
    'Streaming-Angebote finden',
    'Trouver les offres',
    'Trova le offerte',
    'Encontrar ofertas',
    'Find streaming offers',
  ),
  searchCountry: l(
    'Land für deine Suche',
    'Pays de recherche',
    'Paese di ricerca',
    'País de búsqueda',
    'Search country',
  ),
  example: l(
    'Suchbeispiel',
    'Exemple de recherche',
    'Esempio di ricerca',
    'Ejemplo de búsqueda',
    'Example search',
  ),
  accountQ: l(
    'Brauche ich ein Cineradar-Konto?',
    'Faut-il un compte Cineradar ?',
    'Serve un account Cineradar?',
    '¿Necesito una cuenta de Cineradar?',
    'Do I need a Cineradar account?',
  ),
  accountA: l(
    'Nein. Suche und Angebotsvergleich sind kostenlos ohne Konto nutzbar. Deine Merkliste und Anbieterauswahl bleiben in diesem Browser. Sie werden nicht automatisch auf andere Geräte übertragen. Streamingdienste können ein eigenes Konto und Zahlungen verlangen.',
    'Non. La recherche et la comparaison sont gratuites sans compte. Votre liste et vos plateformes restent dans ce navigateur, sans synchronisation automatique entre appareils. Les services de streaming peuvent exiger un compte et un paiement.',
    'No. Ricerca e confronto sono gratuiti e non richiedono un account. Lista e piattaforme preferite restano in questo browser, senza sincronizzazione automatica. I servizi di streaming possono richiedere un account e un pagamento.',
    'No. La búsqueda y comparación son gratuitas y no requieren cuenta. Tu lista y plataformas se guardan en este navegador, sin sincronización automática. Los servicios de streaming pueden exigir cuenta y pago.',
    'No. Search and offer comparison are free without an account. Your watchlist and providers stay in this browser and do not automatically sync to other devices. Streaming services may require their own account and payment.',
  ),
  status: {
    belegt: l('Belegt', 'Vérifié', 'Verificato', 'Verificado', 'Verified'),
    eingeschränkt: l(
      'Mit Einschränkung',
      'Avec réserve',
      'Con limiti',
      'Con límites',
      'Qualified',
    ),
    unbekannt: l(
      'Nicht bestätigt',
      'Non confirmé',
      'Non confermato',
      'Sin confirmar',
      'Unconfirmed',
    ),
    nicht_anwendbar: l(
      'Nicht anwendbar',
      'Sans objet',
      'Non applicabile',
      'No aplicable',
      'Not applicable',
    ),
  },
};
