import { l } from './copy';
import { reviewed, type Comparison, type Claim } from './types';
const deWeb = l(
  'Deutschland · Website',
  'Allemagne · site web',
  'Germania · sito web',
  'Alemania · web',
  'Germany · website',
);
const deApp = l(
  'Deutschland · Android-App',
  'Allemagne · application Android',
  'Germania · app Android',
  'Alemania · app Android',
  'Germany · Android app',
);
const claim = (
  feature: Claim['feature'],
  text: Claim['text'],
  source: string,
  scope = deWeb,
  status: Claim['status'] = 'belegt',
): Claim => ({ feature, text, source, scope, status, checkedAt: reviewed });
export const guides: Comparison[] = [
  {
    id: 'wer-streamt-es',
    brand: 'WerStreamt.es',
    url: 'https://www.werstreamt.es/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Streaming-Suche & Merklisten',
      'Recherche et listes à voir',
      'Ricerca e liste da vedere',
      'Búsqueda y listas',
      'Streaming search & watchlists',
    ),
    intro: l(
      'Du kennst deinen Wunschtitel. Jetzt zählen das passende Angebot und eine Merkliste, die zu deinem Alltag passt. Dieser Vergleich hilft dir, die Suche von zusätzlichen Organisationsfunktionen zu unterscheiden.',
      'Vous connaissez déjà votre titre. Il vous reste à trouver une offre et une liste adaptée à votre usage. Ce comparatif distingue la recherche des fonctions d’organisation supplémentaires.',
      'Hai già scelto il titolo. Ora servono l’offerta giusta e una lista adatta alle tue abitudini. Questo confronto separa la ricerca dalle funzioni aggiuntive di organizzazione.',
      'Ya sabes qué quieres ver. Ahora necesitas la oferta adecuada y una lista que te resulte útil. Esta comparativa distingue la búsqueda de las funciones adicionales de organización.',
      'You already have a title in mind. Now you need a suitable offer and a watchlist that fits your routine. This comparison separates finding a stream from organizing what to watch.',
    ),
    claims: [
      claim(
        'offers',
        l(
          'Filter nach Anbieter, Genre und Preismodell.',
          'Filtres par plateforme, genre et modèle tarifaire.',
          'Filtri per piattaforma, genere e modello di prezzo.',
          'Filtros por plataforma, género y modelo de precio.',
          'Filters for provider, genre and pricing model.',
        ),
        'https://www.werstreamt.es/?cat=9',
      ),
      claim(
        'tracking',
        l(
          'Merkliste, Gesehen-Markierungen und Verfügbarkeitsbenachrichtigungen.',
          'Liste, titres vus et alertes de disponibilité.',
          'Lista, titoli visti e notifiche di disponibilità.',
          'Lista, títulos vistos y avisos de disponibilidad.',
          'Watchlist, watched markers and availability alerts.',
        ),
        'https://play.google.com/store/apps/details?hl=de&id=de.wse.werstreamt.es',
        deApp,
      ),
      claim(
        'cost',
        l(
          'Grundfunktionen kostenlos; Pro ergänzt Werbefreiheit und gemeinsame Watchlists.',
          'Fonctions de base gratuites ; Pro ajoute absence de publicité et listes partagées.',
          'Funzioni base gratuite; Pro aggiunge assenza di pubblicità e liste condivise.',
          'Funciones básicas gratuitas; Pro añade uso sin anuncios y listas compartidas.',
          'Core features are free; Pro adds ad-free use and shared watchlists.',
        ),
        'https://play.google.com/store/apps/details?hl=de&id=de.wse.werstreamt.es',
        deApp,
      ),
    ],
    decision: l(
      'Für die Frage „Wo läuft mein Film?“ kannst du beide Suchwege ausprobieren. Wenn gemeinsame Listen oder automatische Erinnerungen entscheidend sind, prüfe die beschriebenen WerStreamt.es-Funktionen. Cineradar passt zur Suche ohne Konto und zum Speichern auf dem eigenen Gerät; eine gemeinsame Familienliste bietet es derzeit nicht.',
      'Pour savoir où regarder un film, essayez les deux recherches. Si les listes partagées ou les alertes sont essentielles, examinez les fonctions décrites par WerStreamt.es. Cineradar convient à la recherche sans compte et à une liste sur votre appareil, mais ne propose pas de liste familiale partagée.',
      'Per sapere dove vedere un film puoi provare entrambe le ricerche. Se contano liste condivise o avvisi, valuta le funzioni descritte da WerStreamt.es. Cineradar serve per cercare senza account e salvare sul proprio dispositivo; non offre una lista familiare condivisa.',
      'Para saber dónde ver una película, prueba ambas búsquedas. Si necesitas listas compartidas o avisos, revisa las funciones de WerStreamt.es. Cineradar permite buscar sin cuenta y guardar en tu dispositivo; no ofrece una lista familiar compartida.',
      'For finding a film’s streaming offer, try either search. If shared lists or automatic reminders matter, consider the described WerStreamt.es features. Cineradar suits account-free search and saving on your own device; it currently has no shared family watchlist.',
    ),
    question: l(
      'Gehören WerStreamt.es und Cineradar zusammen?',
      'WerStreamt.es et Cineradar sont-ils liés ?',
      'WerStreamt.es e Cineradar sono collegati?',
      '¿WerStreamt.es y Cineradar son lo mismo?',
      'Are WerStreamt.es and Cineradar the same service?',
    ),
    answer: l(
      'Nein. Cineradar wird von Wiresoft AG betrieben. Dieser Vergleich wird von Cineradar veröffentlicht und behauptet keine Partnerschaft mit WerStreamt.es. Die offiziellen Produktlinks führen zum jeweiligen Anbieter.',
      'Non. Cineradar est exploité par Wiresoft AG. Ce comparatif est publié par Cineradar et ne revendique aucun partenariat avec WerStreamt.es. Les liens officiels mènent à chaque fournisseur.',
      'No. Cineradar è gestito da Wiresoft AG. Questo confronto è pubblicato da Cineradar e non dichiara una partnership con WerStreamt.es. I link ufficiali portano ai rispettivi fornitori.',
      'No. Wiresoft AG opera Cineradar. Cineradar publica esta comparativa sin afirmar una asociación con WerStreamt.es. Los enlaces oficiales llevan a cada proveedor.',
      'No. Cineradar is operated by Wiresoft AG. This comparison is published by Cineradar and makes no claim of a partnership with WerStreamt.es. Official links lead to the respective providers.',
    ),
    example: 'Dune',
    related: ['justwatch', 'yidio', 'trakt'],
  },
  {
    id: 'justwatch',
    brand: 'JustWatch',
    url: 'https://www.justwatch.com/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Länder, Anbieter & Angebotsarten',
      'Pays, plateformes et offres',
      'Paesi, piattaforme e offerte',
      'Países, plataformas y ofertas',
      'Countries, providers & offers',
    ),
    intro: l(
      'Bei einer Streaming-Suche macht das Land einen Unterschied. Ebenso wichtig ist, ob ein Treffer im Abo enthalten ist oder extra kostet. Hier vergleichst du diese Entscheidungen, bevor du einen Anbieter öffnest.',
      'Le pays change les résultats d’une recherche de streaming. Il faut aussi savoir si le titre est inclus dans votre abonnement ou facturé en plus. Comparez ces choix avant d’ouvrir une plateforme.',
      'Il paese cambia i risultati della ricerca streaming. Conta anche capire se il titolo è incluso nell’abbonamento o costa a parte. Confronta queste scelte prima di aprire una piattaforma.',
      'El país cambia los resultados de streaming. También importa saber si el título está incluido en tu suscripción o cuesta aparte. Compara estas decisiones antes de abrir la plataforma.',
      'Country affects streaming results. So does whether a title is included in your subscription or costs extra. Compare these choices before opening a provider.',
    ),
    claims: [
      claim(
        'offers',
        l(
          'Streaming, Leihe und Kauf; Filter unter anderem nach Genre und Erscheinungsjahr.',
          'Streaming, location et achat ; filtres de genre et d’année.',
          'Streaming, noleggio e acquisto; filtri per genere e anno.',
          'Streaming, alquiler y compra; filtros de género y año.',
          'Streaming, rental and purchase; filters include genre and release year.',
        ),
        'https://www.justwatch.com/de',
      ),
      claim(
        'countries',
        l(
          'Internationale Länderauswahl mit eigenen Einstiegen für Deutschland, Frankreich, Italien, Spanien und USA.',
          'Sélection internationale avec pages pour Allemagne, France, Italie, Espagne et États-Unis.',
          'Selezione internazionale con pagine per Germania, Francia, Italia, Spagna e USA.',
          'Selección internacional con páginas para Alemania, Francia, Italia, España y EE. UU.',
          'International country selector with entries for Germany, France, Italy, Spain and the US.',
        ),
        'https://www.justwatch.com/',
        l(
          'Internationale Website',
          'Site international',
          'Sito internazionale',
          'Web internacional',
          'International website',
        ),
      ),
    ],
    decision: l(
      'Prüfe bei beiden Diensten zuerst denselben Titel im selben Land. Wenn du außerhalb der fünf Cineradar-Märkte suchst, beginne bei JustWatch mit der Länderauswahl. Innerhalb dieser Märkte kannst du bei Cineradar Oberflächensprache und Angebotsland getrennt wählen und Zusatzkanäle getrennt von deinem Basisabo betrachten.',
      'Comparez d’abord le même titre dans le même pays. Hors des cinq marchés de Cineradar, commencez par le sélecteur de pays de JustWatch. Dans ces marchés, Cineradar permet de séparer langue d’interface, pays des offres et chaînes supplémentaires de l’abonnement de base.',
      'Confronta prima lo stesso titolo nello stesso paese. Fuori dai cinque mercati di Cineradar, parti dalla selezione del paese di JustWatch. Nei mercati supportati, Cineradar separa lingua, paese delle offerte e canali aggiuntivi dall’abbonamento base.',
      'Compara primero el mismo título en el mismo país. Fuera de los cinco mercados de Cineradar, empieza por el selector de país de JustWatch. En los mercados compatibles, Cineradar separa idioma, país de las ofertas y canales adicionales de la suscripción básica.',
      'Start with the same title in the same country on both services. Outside Cineradar’s five markets, check JustWatch’s country selector first. Within those markets, Cineradar separates interface language, offer country and add-on channels from your base subscription.',
    ),
    question: l(
      'Warum ist Prime Video nicht immer im Prime-Abo enthalten?',
      'Pourquoi une offre Prime Video peut-elle coûter plus cher ?',
      'Perché un’offerta Prime Video può costare a parte?',
      '¿Por qué una oferta de Prime Video puede costar aparte?',
      'Why can a Prime Video offer cost extra?',
    ),
    answer: l(
      'Ein Anbieter kann Abo-Titel, Leih- und Kaufangebote sowie zusätzliche Channels führen. Ein Anbieterlogo allein sagt daher nicht, ob dein vorhandenes Abo ausreicht. Prüfe Angebotsart, Staffel und gegebenenfalls den benötigten Zusatzkanal.',
      'Une plateforme peut proposer abonnement, location, achat et chaînes supplémentaires. Son logo ne suffit pas à prouver que votre abonnement couvre le titre. Vérifiez le type d’offre, la saison et la chaîne requise.',
      'Una piattaforma può offrire abbonamento, noleggio, acquisto e canali aggiuntivi. Il logo non dimostra che il tuo abbonamento basti. Controlla tipo di offerta, stagione ed eventuale canale richiesto.',
      'Una plataforma puede ofrecer suscripción, alquiler, compra y canales adicionales. Su logo no prueba que tu suscripción cubra el título. Comprueba tipo de oferta, temporada y canal necesario.',
      'A provider can offer subscription titles, rentals, purchases and add-on channels. Its logo alone does not show that your current subscription is enough. Check the offer type, season and any required add-on.',
    ),
    example: 'Reacher',
    related: ['wer-streamt-es', 'reelgood', 'movie-of-the-night'],
  },
  {
    id: 'playpilot',
    brand: 'PlayPilot',
    url: 'https://www.playpilot.com/de/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Entdecken & gemeinsam auswählen',
      'Découvrir et choisir ensemble',
      'Scoprire e scegliere insieme',
      'Descubrir y elegir juntos',
      'Discovery & choosing together',
    ),
    intro: l(
      'Noch keine Idee für heute Abend? Oder schon einen konkreten Film im Kopf? Der Unterschied zwischen Inspiration und gezielter Angebotssuche entscheidet, welche Oberfläche dir hilft.',
      'Aucune idée pour ce soir, ou déjà un film précis en tête ? Le choix entre inspiration et recherche d’une offre détermine l’outil le plus utile.',
      'Non sai cosa guardare oppure hai già un film in mente? La differenza tra ispirazione e ricerca mirata determina quale strumento ti aiuta.',
      '¿No sabes qué ver o ya tienes una película en mente? La diferencia entre inspiración y búsqueda concreta determina qué herramienta te conviene.',
      'No idea what to watch, or already have a film in mind? The difference between inspiration and finding a specific offer determines which interface helps.',
    ),
    claims: [
      claim(
        'discover',
        l(
          'Auswahl nach beliebt, neu und am besten bewertet.',
          'Sélections populaires, récentes et les mieux notées.',
          'Selezioni popolari, nuove e meglio valutate.',
          'Selecciones populares, nuevas y mejor valoradas.',
          'Popular, new and top-rated selections.',
        ),
        'https://www.playpilot.com/de/',
      ),
      claim(
        'watchlist',
        l(
          'Kostenloses Konto zum Speichern, Tracken und Folgen von Freunden.',
          'Compte gratuit pour enregistrer, suivre les titres et les amis.',
          'Account gratuito per salvare, seguire titoli e amici.',
          'Cuenta gratuita para guardar y seguir títulos y amigos.',
          'Free account for saving, tracking and following friends.',
        ),
        'https://www.playpilot.com/de/',
      ),
    ],
    decision: l(
      'Wenn du Filmtipps über andere Menschen finden möchtest, sind soziale Funktionen ein relevantes Kriterium. Für die anschließende Frage nach Abo, Leihe oder Zusatzkanal kannst du Cineradar ohne Konto nutzen. Eine lokale Merkliste ist dabei praktisch für ein Gerät; sie ersetzt kein soziales Profil.',
      'Pour trouver des idées grâce à d’autres personnes, les fonctions sociales comptent. Pour ensuite vérifier abonnement, location ou chaîne supplémentaire, Cineradar fonctionne sans compte. Sa liste locale convient à un appareil ; elle ne remplace pas un profil social.',
      'Se cerchi consigli attraverso altre persone, le funzioni sociali contano. Per verificare poi abbonamento, noleggio o canale aggiuntivo, Cineradar funziona senza account. La lista locale è utile su un dispositivo, ma non sostituisce un profilo sociale.',
      'Si buscas ideas a través de otras personas, las funciones sociales importan. Para comprobar después suscripción, alquiler o canal adicional, Cineradar funciona sin cuenta. Su lista local sirve en un dispositivo, pero no sustituye un perfil social.',
      'If you find film ideas through other people, social features matter. For the next step of checking subscription, rental or add-on access, Cineradar works without an account. Its local watchlist is useful on one device; it does not replace a social profile.',
    ),
    question: l(
      'Sind Cineradars Empfehlungen auf meinen Geschmack trainiert?',
      'Les recommandations Cineradar apprennent-elles mes goûts ?',
      'I consigli di Cineradar imparano i miei gusti?',
      '¿Cineradar aprende mis gustos?',
      'Are Cineradar recommendations trained on my taste?',
    ),
    answer: l(
      'Nein. Die Auswahl nutzt Katalogdaten, Genres, Aktualität und deine gewählten Anbieter. Cineradar führt kein persönliches Bewertungsprofil und folgt keinen Freunden. Für eine gezielte Auswahl kannst du Genre, Laufzeit und Anbieter filtern.',
      'Non. La sélection utilise catalogue, genres, nouveautés et plateformes choisies. Cineradar n’a pas de profil personnel de notes ni de suivi d’amis. Vous pouvez filtrer par genre, durée et plateforme.',
      'No. La selezione usa catalogo, generi, novità e piattaforme scelte. Cineradar non crea un profilo personale di voti e non segue amici. Puoi filtrare per genere, durata e piattaforma.',
      'No. La selección usa catálogo, géneros, novedades y plataformas elegidas. Cineradar no crea un perfil personal de valoraciones ni sigue amigos. Puedes filtrar por género, duración y plataforma.',
      'No. Selection uses catalog data, genres, recency and your chosen providers. Cineradar has no personal rating profile or friend-following system. You can filter by genre, runtime and provider.',
    ),
    example: 'Dune: Part Two',
    related: ['moviepilot', 'movie-of-the-night', 'plex'],
  },
  {
    id: 'moviepilot',
    brand: 'Moviepilot',
    url: 'https://www.moviepilot.de/streaming/neuerscheinungen',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Filmcommunity & Streaming-Angebote',
      'Communauté cinéma et offres',
      'Community cinema e offerte',
      'Comunidad cinéfila y ofertas',
      'Film community & streaming offers',
    ),
    intro: l(
      'Ein guter Filmtipp und ein verfügbares Streamingangebot beantworten verschiedene Fragen. Nutze diesen Vergleich, um redaktionelle Orientierung mit dem nächsten Schritt zum Filmabend zu verbinden.',
      'Une recommandation et une offre disponible répondent à des questions différentes. Ce comparatif relie l’orientation éditoriale à l’étape suivante : regarder le film.',
      'Un consiglio e un’offerta disponibile rispondono a domande diverse. Questo confronto collega l’orientamento editoriale al passo successivo: guardare il film.',
      'Una recomendación y una oferta disponible responden a preguntas distintas. Esta comparativa conecta la orientación editorial con el siguiente paso: ver la película.',
      'A good film recommendation and an available streaming offer answer different questions. Use this comparison to connect editorial guidance with the next step of watching.',
    ),
    claims: [
      claim(
        'discover',
        l(
          'Community-Charts, Streaming-Neuheiten und redaktionelle Streaming-News.',
          'Classements communautaires, nouveautés et actualités éditoriales du streaming.',
          'Classifiche della community, novità e notizie editoriali sullo streaming.',
          'Listas de la comunidad, novedades y noticias editoriales de streaming.',
          'Community charts, new streaming releases and editorial streaming news.',
        ),
        'https://www.moviepilot.de/streaming/neuerscheinungen',
      ),
      claim(
        'offers',
        l(
          'Anbieterauswahl sowie getrennte Einstiege für Filme und Serien.',
          'Choix des plateformes et entrées distinctes films et séries.',
          'Selezione delle piattaforme e accessi separati per film e serie.',
          'Selección de plataformas y entradas separadas para películas y series.',
          'Provider selection and separate film and show sections.',
        ),
        'https://www.moviepilot.de/streaming/neuerscheinungen',
      ),
    ],
    decision: l(
      'Lies eine redaktionelle Empfehlung, wenn du wissen möchtest, warum ein Film interessant sein könnte. Sobald deine Wahl steht, suche den genauen Titel und das richtige Jahr in Cineradar. Ein Streaming-Finder ergänzt die Einordnung; er ersetzt weder Filmkritik noch Diskussionen mit einer Community.',
      'Lisez une recommandation pour comprendre l’intérêt d’un film. Une fois votre choix fait, cherchez son titre exact et son année dans Cineradar. Un guide de disponibilité complète cette lecture sans remplacer critique ou discussion.',
      'Leggi un consiglio per capire perché un film potrebbe interessarti. Una volta scelto, cerca titolo esatto e anno su Cineradar. Una guida alla disponibilità completa la lettura senza sostituire critica o discussioni.',
      'Lee una recomendación para entender por qué una película puede interesarte. Después busca el título exacto y el año en Cineradar. Una guía de disponibilidad complementa esa lectura sin sustituir críticas ni debates.',
      'Read editorial recommendations to understand why a film might interest you. Once you choose, search its exact title and year on Cineradar. An availability guide complements that context without replacing film criticism or community discussion.',
    ),
    question: l(
      'Kann ich bei Cineradar eigene Filmkritiken veröffentlichen?',
      'Puis-je publier des critiques sur Cineradar ?',
      'Posso pubblicare recensioni su Cineradar?',
      '¿Puedo publicar críticas en Cineradar?',
      'Can I publish film reviews on Cineradar?',
    ),
    answer: l(
      'Derzeit nicht. Cineradar konzentriert sich auf Titeldaten und die Suche nach Angeboten. Bewertungen aus den Quelldaten sind keine Cineradar-Nutzerbewertungen. Du kannst Titel speichern und unzutreffende Angebotsdaten über die Detailseite melden.',
      'Pas actuellement. Cineradar se concentre sur les titres et leurs offres. Les notes des sources ne sont pas des avis d’utilisateurs Cineradar. Vous pouvez enregistrer un titre et signaler une offre incorrecte depuis sa fiche.',
      'Al momento no. Cineradar si concentra sui titoli e le offerte. I voti delle fonti non sono recensioni di utenti Cineradar. Puoi salvare un titolo e segnalare offerte errate dalla sua scheda.',
      'Actualmente no. Cineradar se centra en títulos y ofertas. Las valoraciones de las fuentes no son opiniones de usuarios de Cineradar. Puedes guardar un título e informar de ofertas incorrectas desde su ficha.',
      'Not currently. Cineradar focuses on title information and finding offers. Source ratings are not Cineradar user reviews. You can save titles and report incorrect offer data from a detail page.',
    ),
    example: 'Dune',
    related: ['playpilot', 'tv-movie', 'justwatch'],
  },
  {
    id: 'tv-movie',
    brand: 'TV Movie',
    url: 'https://www.tvmovie.de/wer-streamt',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Streaming-Finder im Medienportal',
      'Recherche dans un portail média',
      'Ricerca in un portale editoriale',
      'Buscador en un portal de medios',
      'Streaming search within a media portal',
    ),
    intro: l(
      'Du möchtest einen Titel aus einem Artikel oder dem Fernsehprogramm streamen. Entscheidend sind eine eindeutige Titelsuche und verständliche Filter. Hier geht es um den Streaming-Finder, nicht um einen Vergleich der gesamten TV-Berichterstattung.',
      'Vous voulez regarder en streaming un titre aperçu dans un article ou le programme télé. Il vous faut une recherche précise et des filtres clairs. Ce comparatif porte sur le guide de streaming, pas sur toute la couverture télévisée.',
      'Vuoi vedere in streaming un titolo trovato in un articolo o nella guida TV. Servono ricerca precisa e filtri chiari. Il confronto riguarda il motore streaming, non l’intera informazione televisiva.',
      'Quieres ver en streaming un título que encontraste en un artículo o la programación de televisión. Necesitas búsqueda precisa y filtros claros. Comparamos el buscador de streaming, no toda la cobertura televisiva.',
      'You want to stream a title you saw in an article or TV schedule. Accurate title matching and understandable filters matter. This comparison covers the streaming finder, not the portal’s entire TV coverage.',
    ),
    claims: [
      claim(
        'offers',
        l(
          'Titelsuche und Filter nach Anbieter, Genre und Abo.',
          'Recherche par titre et filtres plateforme, genre et abonnement.',
          'Ricerca per titolo e filtri piattaforma, genere e abbonamento.',
          'Búsqueda por título y filtros de plataforma, género y suscripción.',
          'Title search and provider, genre and subscription filters.',
        ),
        'https://www.tvmovie.de/wer-streamt',
      ),
      claim(
        'discover',
        l(
          'Streaming-Finder innerhalb des TV- und Unterhaltungsportals.',
          'Guide de streaming intégré au portail TV et divertissement.',
          'Ricerca streaming nel portale TV e intrattenimento.',
          'Buscador de streaming dentro del portal de televisión y entretenimiento.',
          'Streaming finder within the TV and entertainment portal.',
        ),
        'https://www.tvmovie.de/wer-streamt',
      ),
    ],
    decision: l(
      'Wenn du bereits im TV-Portal liest, kannst du dort mit der Titelsuche beginnen. Für die separate Prüfung eines Angebotslandes und zusätzlicher Channels ist Cineradars Angebotsansicht ein weiterer Suchweg. Gleiche Titel anhand des Jahres ab, besonders bei Neuverfilmungen.',
      'Si vous lisez déjà le portail TV, commencez par sa recherche. Pour vérifier séparément le pays et les chaînes supplémentaires, essayez aussi les offres de Cineradar. Confirmez l’année, surtout pour les nouvelles adaptations.',
      'Se stai già leggendo il portale TV, puoi iniziare dalla sua ricerca. Per verificare paese e canali aggiuntivi separatamente, prova anche le offerte Cineradar. Controlla l’anno, soprattutto nei remake.',
      'Si ya estás leyendo el portal de televisión, puedes empezar por su búsqueda. Para revisar país y canales adicionales por separado, prueba también Cineradar. Confirma el año, especialmente en las nuevas versiones.',
      'If you are already reading the TV portal, start with its search. For separately checking the offer country and add-on channels, Cineradar provides another route. Match the release year, especially for remakes.',
    ),
    question: l(
      'Ist ein TV-Sendetermin dasselbe wie ein Streamingangebot?',
      'Un horaire TV équivaut-il à une offre de streaming ?',
      'Un orario TV equivale a un’offerta streaming?',
      '¿Un horario de televisión equivale a una oferta de streaming?',
      'Is a TV broadcast time the same as a streaming offer?',
    ),
    answer: l(
      'Nein. Ein linearer Sendetermin belegt keine anschließend abrufbare Mediathek-Version. Prüfe den Titel gesondert im gewünschten Land. Ein fehlender Treffer bei Cineradar bedeutet, dass im erfassten Datenstand kein passendes Ergebnis vorliegt, nicht dass ein Titel weltweit nicht existiert.',
      'Non. Une diffusion télé ne prouve pas une disponibilité ultérieure en replay. Vérifiez le titre dans le pays souhaité. L’absence de résultat sur Cineradar concerne les données recensées, pas l’existence du titre dans le monde.',
      'No. Una trasmissione TV non prova la successiva disponibilità on demand. Verifica il titolo nel paese desiderato. Nessun risultato su Cineradar riguarda i dati raccolti, non l’esistenza del titolo nel mondo.',
      'No. Una emisión de televisión no prueba que después esté disponible a la carta. Comprueba el título en tu país. La ausencia de resultados en Cineradar se refiere a los datos disponibles, no a la existencia del título en el mundo.',
      'No. A scheduled broadcast does not prove later on-demand availability. Check the title separately in your country. No Cineradar result means no match in the catalog data collected, not that the title does not exist worldwide.',
    ),
    example: 'The Last of Us',
    related: ['moviepilot', 'wer-streamt-es', 'justwatch'],
  },
];
