import { l } from './copy';
import { reviewed, type Comparison, type Claim } from './types';
const web = l(
  'Website · Funktionsbeschreibung',
  'Site web · description des fonctions',
  'Sito web · descrizione delle funzioni',
  'Web · descripción de funciones',
  'Website · feature description',
);
const claim = (
  feature: Claim['feature'],
  text: Claim['text'],
  source: string,
  scope = web,
  status: Claim['status'] = 'belegt',
): Claim => ({ feature, text, source, scope, status, checkedAt: reviewed });
export const specialists: Comparison[] = [
  {
    id: 'movie-of-the-night',
    brand: 'Movie of the Night',
    url: 'https://www.movieofthenight.com/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Empfehlungen & gemeinsame Datenquelle',
      'Recommandations et source commune',
      'Consigli e fonte condivisa',
      'Recomendaciones y fuente compartida',
      'Recommendations & a shared data source',
    ),
    intro: l(
      'Eine Datenquelle kann mehrere unterschiedliche Sucherlebnisse ermöglichen. Entscheidend ist, wie du auswählst, Listen verwendest und Angebote einordnest. Hier vergleichen wir die Websites und erklären die Verbindung zur Streaming Availability API.',
      'Une source de données peut alimenter différentes expériences. Ce qui compte est votre manière de choisir, d’utiliser les listes et de lire les offres. Nous comparons les sites et expliquons le lien avec Streaming Availability API.',
      'Una fonte può alimentare esperienze diverse. Contano il modo di scegliere, usare le liste e leggere le offerte. Confrontiamo i siti e spieghiamo il legame con Streaming Availability API.',
      'Una fuente puede alimentar experiencias diferentes. Importa cómo eliges, usas listas e interpretas ofertas. Comparamos las webs y explicamos la relación con Streaming Availability API.',
      'One data source can support different search experiences. What matters is how you choose, use lists and interpret offers. We compare the websites and explain the connection to Streaming Availability API.',
    ),
    claims: [
      claim(
        'discover',
        l(
          'Empfehlungssuche für Filme und Serien.',
          'Moteur de recommandations de films et séries.',
          'Motore di consigli per film e serie.',
          'Motor de recomendaciones de películas y series.',
          'Movie and series recommendation engine.',
        ),
        'https://www.movieofthenight.com/about',
      ),
      claim(
        'watchlist',
        l(
          'Konten ermöglichen Listen und geräteübergreifende Einstellungen.',
          'Les comptes permettent listes et préférences entre appareils.',
          'Gli account consentono liste e preferenze tra dispositivi.',
          'Las cuentas permiten listas y preferencias entre dispositivos.',
          'Accounts enable lists and cross-device preferences.',
        ),
        'https://www.movieofthenight.com/about',
      ),
      claim(
        'data',
        l(
          'Betreibt die Streaming Availability API.',
          'Exploite Streaming Availability API.',
          'Gestisce Streaming Availability API.',
          'Opera Streaming Availability API.',
          'Operates Streaming Availability API.',
        ),
        'https://docs.movieofthenight.com/',
      ),
    ],
    decision: l(
      'Wähle nach dem Ablauf, den du brauchst: Empfehlungen und ein Konto für mehrere Geräte oder eine Suche mit lokaler Merkliste. Cineradar nutzt die Streaming Availability API, importiert Daten aber in einen eigenen Katalog. Daraus folgt weder eine größere Auswahl noch ein identischer Aktualisierungsstand.',
      'Choisissez selon votre usage : recommandations et compte multi-appareils, ou recherche avec liste locale. Cineradar utilise Streaming Availability API mais importe dans son propre catalogue. Cela ne prouve ni une sélection plus large ni une fraîcheur identique.',
      'Scegli in base all’uso: consigli e account su più dispositivi oppure ricerca con lista locale. Cineradar usa Streaming Availability API ma importa in un proprio catalogo. Questo non dimostra né più scelta né aggiornamenti identici.',
      'Elige según tu uso: recomendaciones y cuenta en varios dispositivos, o búsqueda con lista local. Cineradar usa Streaming Availability API, pero importa a su propio catálogo. Eso no demuestra más selección ni la misma actualización.',
      'Choose around your workflow: recommendations and a multi-device account, or search with a local watchlist. Cineradar uses Streaming Availability API but imports into its own catalog. That proves neither a larger selection nor an identical update time.',
    ),
    question: l(
      'Brauche ich für Cineradar einen API-Schlüssel?',
      'Faut-il une clé API pour Cineradar ?',
      'Serve una chiave API per Cineradar?',
      '¿Necesito una clave API para Cineradar?',
      'Do I need an API key to use Cineradar?',
    ),
    answer: l(
      'Nein. Die normale Titelsuche funktioniert ohne API-Konto. Cineradar kümmert sich serverseitig um seine Datenanbindung. Die kostenpflichtigen Entwicklerangebote von Movie of the Night sind ein separates Produkt und keine Voraussetzung für deinen Filmabend.',
      'Non. La recherche fonctionne sans compte API. Cineradar gère sa connexion côté serveur. Les offres développeurs payantes de Movie of the Night sont un produit distinct, inutile pour votre soirée cinéma.',
      'No. La ricerca funziona senza account API. Cineradar gestisce la connessione sul server. Le offerte a pagamento per sviluppatori di Movie of the Night sono un prodotto separato, non necessario per guardare un film.',
      'No. La búsqueda funciona sin cuenta API. Cineradar gestiona la conexión en el servidor. Las ofertas de pago para desarrolladores de Movie of the Night son otro producto y no son necesarias para tu noche de cine.',
      'No. Normal title search works without an API account. Cineradar handles its data connection on the server. Movie of the Night’s paid developer offerings are a separate product, not a prerequisite for your movie night.',
    ),
    example: 'Dune',
    related: ['playpilot', 'justwatch', 'reelgood'],
  },
  {
    id: 'reelgood',
    brand: 'Reelgood',
    url: 'https://reelgood.com/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Regionale Nutzbarkeit zuerst prüfen',
      'Vérifier d’abord la région',
      'Verificare prima la regione',
      'Comprueba primero la región',
      'Check regional access first',
    ),
    intro: l(
      'Ein internationaler Datenanbieter und seine Endnutzer-App müssen nicht dieselben Länder unterstützen. Prüfe deshalb zuerst die regionale Nutzbarkeit. Dieser Vergleich trennt bestätigte App-Funktionen von noch nicht bestätigter Länderabdeckung.',
      'Un fournisseur international de données et son application grand public ne couvrent pas forcément les mêmes pays. Vérifiez d’abord l’accès régional. Ce comparatif distingue fonctions confirmées et couverture non confirmée.',
      'Un fornitore internazionale di dati e la sua app consumer non coprono necessariamente gli stessi paesi. Verifica prima l’accesso regionale. Il confronto distingue funzioni confermate e copertura non confermata.',
      'Un proveedor internacional de datos y su app para usuarios no cubren necesariamente los mismos países. Comprueba primero el acceso regional. Distinguimos funciones confirmadas y cobertura sin confirmar.',
      'An international data provider and its consumer app do not necessarily support the same countries. Check regional access first. This comparison separates confirmed app features from unconfirmed country coverage.',
    ),
    claims: [
      claim(
        'tracking',
        l(
          'iOS-Beschreibung nennt Titellisten, Serien-Tracking und Verfügbarkeitsalarme.',
          'La description iOS indique listes, suivi des séries et alertes.',
          'La descrizione iOS indica liste, tracciamento serie e avvisi.',
          'La descripción de iOS indica listas, seguimiento de series y avisos.',
          'The iOS description lists watchlists, series tracking and availability alerts.',
        ),
        'https://apps.apple.com/us/app/reelgood-streaming-guide/id1031391869',
        l(
          'US App Store · iOS',
          'App Store US · iOS',
          'App Store USA · iOS',
          'App Store EE. UU. · iOS',
          'US App Store · iOS',
        ),
      ),
      claim(
        'countries',
        l(
          'Beim Aufruf aus Deutschland zeigte die Website US-Streamingdienste und einen regionalen Verfügbarkeitshinweis. Ein deutscher Angebotskatalog wurde dabei nicht bestätigt.',
          'Depuis l’Allemagne, le site affichait des services américains et une réserve régionale. Aucun catalogue allemand n’a été confirmé lors de cette vérification.',
          'Dalla Germania il sito mostrava servizi USA e un avviso regionale. La verifica non ha confermato un catalogo tedesco.',
          'Desde Alemania, la web mostró servicios de EE. UU. y un aviso regional. La revisión no confirmó un catálogo alemán.',
          'Accessed from Germany, the website displayed US services and a regional availability notice. This check did not confirm a German offer catalog.',
        ),
        'https://reelgood.com/',
        l(
          'Webaufruf aus Deutschland',
          'Accès web depuis l’Allemagne',
          'Accesso web dalla Germania',
          'Acceso web desde Alemania',
          'Website access from Germany',
        ),
        'eingeschränkt',
      ),
    ],
    decision: l(
      'Für eine englische Suche in den USA kannst du Cineradar direkt mit dem US-Katalog nutzen. In Deutschland, Frankreich, Italien und Spanien sind eigene Angebotsländer auswählbar. Wer Reelgood nutzen möchte, sollte das Land in der tatsächlichen App prüfen; eine im Store verfügbare App beweist noch keinen lokalen Streamingkatalog.',
      'Pour une recherche en anglais aux États-Unis, Cineradar ouvre son catalogue américain. Allemagne, France, Italie et Espagne sont aussi sélectionnables. Pour Reelgood, vérifiez le pays dans l’application : sa présence dans un magasin ne prouve pas un catalogue local.',
      'Per cercare in inglese negli USA, Cineradar apre il catalogo americano. Sono selezionabili anche Germania, Francia, Italia e Spagna. Per Reelgood verifica il paese nell’app: la presenza nello store non prova un catalogo locale.',
      'Para buscar en inglés en EE. UU., Cineradar abre el catálogo estadounidense. También puedes elegir Alemania, Francia, Italia y España. Para Reelgood comprueba el país en la app: estar en una tienda no demuestra un catálogo local.',
      'For English-language search in the US, Cineradar opens its US catalog. Germany, France, Italy and Spain are also selectable. If you want Reelgood, check the country inside the app: an app-store listing alone does not establish local streaming coverage.',
    ),
    question: l(
      'Beweist Reelgoods internationale Datenabdeckung die Länder der App?',
      'Les données internationales prouvent-elles les pays de l’app ?',
      'I dati internazionali provano i paesi dell’app?',
      '¿Los datos internacionales prueban los países de la app?',
      'Does international data coverage prove app coverage?',
    ),
    answer: l(
      'Nein. Das Geschäftskundenangebot von Reelgood ist von der Endnutzeroberfläche zu unterscheiden. Wir übertragen dessen Länderangaben nicht auf die App. Die aktuelle regionale Prüfung bleibt deshalb ausdrücklich eingeschränkt.',
      'Non. L’offre professionnelle de Reelgood est distincte de l’interface grand public. Nous n’attribuons pas ses pays à l’application. La vérification régionale reste donc explicitement limitée.',
      'No. L’offerta professionale Reelgood è distinta dall’interfaccia consumer. Non attribuiamo i suoi paesi all’app. La verifica regionale resta quindi esplicitamente limitata.',
      'No. La oferta profesional de Reelgood es distinta de la interfaz para usuarios. No atribuimos sus países a la app. La comprobación regional sigue expresamente limitada.',
      'No. Reelgood’s business offering is separate from its consumer interface. We do not attribute its listed countries to the app. The regional review therefore remains explicitly limited.',
    ),
    example: 'Severance',
    related: ['justwatch', 'yidio', 'movie-of-the-night'],
  },
  {
    id: 'yidio',
    brand: 'Yidio',
    url: 'https://www.yidio.com/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Dienstübergreifende Suche & Erinnerungen',
      'Recherche multi-services et rappels',
      'Ricerca multiservizio e promemoria',
      'Búsqueda entre servicios y recordatorios',
      'Cross-service search & reminders',
    ),
    intro: l(
      'Titel an einem Ort sammeln und später wiederfinden: Dafür ist nicht jede Merkliste gleich geeignet. Vergleiche die Suche, Erinnerungen und den Weg zum tatsächlichen Streamingdienst, bevor du dich für einen Guide entscheidest.',
      'Rassembler des titres puis les retrouver : toutes les listes ne répondent pas au même besoin. Comparez recherche, rappels et accès au service réel avant de choisir votre guide.',
      'Raccogliere titoli e ritrovarli: non tutte le liste servono allo stesso scopo. Confronta ricerca, promemoria e passaggio alla piattaforma prima di scegliere una guida.',
      'Guardar títulos y recuperarlos después: no todas las listas sirven igual. Compara búsqueda, recordatorios y acceso al servicio real antes de elegir una guía.',
      'Collecting titles and finding them later: watchlists differ in what they offer. Compare search, reminders and the path to the actual streaming provider before choosing a guide.',
    ),
    claims: [
      claim(
        'watchlist',
        l(
          'Persönliche Watchlist und Empfehlungen.',
          'Liste personnelle et recommandations.',
          'Lista personale e consigli.',
          'Lista personal y recomendaciones.',
          'Personal watchlist and recommendations.',
        ),
        'https://www.yidio.com/',
      ),
      claim(
        'tracking',
        l(
          'Tägliche Erinnerungen; Premium nennt Echtzeit-Erinnerungen und Werbefreiheit.',
          'Rappels quotidiens ; Premium décrit rappels immédiats et absence de publicité.',
          'Promemoria giornalieri; Premium indica avvisi immediati e assenza di pubblicità.',
          'Recordatorios diarios; Premium indica avisos inmediatos y ausencia de anuncios.',
          'Daily reminders; Premium describes real-time reminders and ad-free use.',
        ),
        'https://help.yidio.com/support/solutions/articles/16000061049-what-is-yidio-',
      ),
      claim(
        'countries',
        l(
          'Die geprüfte englische Website zeigt US-Dienste. Ein deutscher, französischer, italienischer oder spanischer Angebotskatalog ist durch die geprüften Quellen nicht bestätigt.',
          'Le site anglais vérifié affiche des services américains. Les sources ne confirment pas de catalogue allemand, français, italien ou espagnol.',
          'Il sito inglese verificato mostra servizi USA. Le fonti non confermano cataloghi tedesco, francese, italiano o spagnolo.',
          'La web inglesa revisada muestra servicios de EE. UU. Las fuentes no confirman catálogos alemán, francés, italiano o español.',
          'The reviewed English website shows US services. The checked sources do not confirm German, French, Italian or Spanish offer catalogs.',
        ),
        'https://www.yidio.com/',
        web,
        'eingeschränkt',
      ),
    ],
    decision: l(
      'Wenn du automatische Erinnerungen möchtest, prüfe Yidios beschriebenen Funktions- und Tarifumfang. Für eine einzelne Suche ohne Registrierung kannst du Cineradar verwenden und das Angebotsland direkt festlegen. Bei beiden Wegen ist der Streamingzugang eine separate Frage: Eine Guide-Mitgliedschaft ersetzt kein Anbieterabo.',
      'Pour des rappels automatiques, examinez les fonctions et offres décrites par Yidio. Pour une recherche sans inscription, Cineradar permet de fixer directement le pays. L’accès au streaming reste distinct : une adhésion au guide ne remplace pas un abonnement à la plateforme.',
      'Per promemoria automatici, valuta funzioni e piani descritti da Yidio. Per una ricerca senza registrazione, Cineradar permette di scegliere direttamente il paese. L’accesso streaming resta separato: l’iscrizione alla guida non sostituisce l’abbonamento alla piattaforma.',
      'Si quieres recordatorios automáticos, revisa las funciones y planes de Yidio. Para una búsqueda sin registro, Cineradar permite elegir directamente el país. El acceso al streaming es independiente: suscribirse a la guía no sustituye la suscripción a la plataforma.',
      'If you want automatic reminders, check Yidio’s described features and plans. For a search without registration, Cineradar lets you set the offer country directly. Streaming access is separate in either workflow: a guide membership does not replace a provider subscription.',
    ),
    question: l(
      'Spielt Cineradar Filme wie ein Streamingdienst ab?',
      'Cineradar diffuse-t-il les films ?',
      'Cineradar riproduce i film?',
      '¿Cineradar reproduce películas?',
      'Does Cineradar play movies like a streaming service?',
    ),
    answer: l(
      'Nein. Cineradar hilft dir, passende Angebote zu finden, und leitet dich über einen Angebotslink weiter. Der jeweilige Dienst übernimmt Wiedergabe, Anmeldung, Altersprüfung und Abrechnung. Prüfe dessen Bedingungen vor einem Abschluss.',
      'Non. Cineradar trouve des offres puis vous y dirige. Le service concerné gère lecture, connexion, contrôle d’âge et paiement. Vérifiez ses conditions avant de souscrire.',
      'No. Cineradar trova le offerte e ti indirizza al servizio, che gestisce riproduzione, accesso, verifica dell’età e pagamento. Leggi le condizioni prima di sottoscrivere.',
      'No. Cineradar encuentra ofertas y te dirige al servicio, que gestiona reproducción, acceso, verificación de edad y cobro. Comprueba las condiciones antes de contratar.',
      'No. Cineradar helps find offers and links to them. The provider handles playback, sign-in, age checks and billing. Check its terms before subscribing or paying.',
    ),
    example: 'The Bear',
    related: ['reelgood', 'wer-streamt-es', 'justwatch'],
  },
  {
    id: 'plex',
    brand: 'Plex Discover',
    url: 'https://www.plex.tv/discover/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Discover & universelle Watchlist',
      'Discover et liste universelle',
      'Discover e lista universale',
      'Discover y lista universal',
      'Discover & universal watchlist',
    ),
    intro: l(
      'Hier geht es um Plex Discover und die universelle Watchlist: einen Titel finden, vormerken und seine Quellen prüfen. Private Medienserver, Transcoding und die Verwaltung eigener Dateien gehören nicht zu diesem Vergleich.',
      'Nous comparons Plex Discover et sa liste universelle : trouver un titre, le conserver et vérifier ses sources. Serveurs personnels, transcodage et gestion de fichiers sont hors périmètre.',
      'Confrontiamo Plex Discover e la lista universale: trovare un titolo, salvarlo e verificarne le fonti. Server personali, transcodifica e gestione dei file sono fuori ambito.',
      'Comparamos Plex Discover y su lista universal: encontrar títulos, guardarlos y comprobar sus fuentes. Servidores personales, transcodificación y gestión de archivos quedan fuera.',
      'This comparison covers Plex Discover and its universal watchlist: finding a title, saving it and checking its sources. Personal media servers, transcoding and file management are outside its scope.',
    ),
    claims: [
      claim(
        'watchlist',
        l(
          'Universelle Watchlist verbindet Titel aus Streamingdiensten und unterstützten Plex-Bibliotheken.',
          'La liste universelle réunit streaming et bibliothèques Plex compatibles.',
          'La lista universale unisce streaming e librerie Plex compatibili.',
          'La lista universal reúne streaming y bibliotecas Plex compatibles.',
          'Universal watchlist combines streaming titles and supported Plex libraries.',
        ),
        'https://support.plex.tv/articles/universal-watchlist/',
      ),
      claim(
        'discover',
        l(
          'Discover bietet Suche, Anbieterauswahl und soziale Funktionen.',
          'Discover propose recherche, plateformes et fonctions sociales.',
          'Discover offre ricerca, piattaforme e funzioni sociali.',
          'Discover ofrece búsqueda, plataformas y funciones sociales.',
          'Discover offers search, provider selection and social features.',
        ),
        'https://www.plex.tv/discover/',
      ),
    ],
    decision: l(
      'Wenn du bereits eine Plex-Bibliothek verwendest, kann eine zentrale Watchlist für deine verschiedenen Quellen sinnvoll sein. Cineradar bietet einen getrennten Webzugang zur Streaming-Suche mit eigenem Länderbezug. Es verbindet sich nicht mit deinem Plex-Server und ist kein Ersatz für dessen Medienverwaltung.',
      'Si vous utilisez une bibliothèque Plex, une liste centrale peut réunir vos sources. Cineradar offre une recherche web séparée avec un pays explicite. Il ne se connecte pas à votre serveur Plex et ne remplace pas sa gestion des médias.',
      'Se usi una libreria Plex, una lista centrale può riunire le tue fonti. Cineradar offre una ricerca web separata con un paese esplicito. Non si collega al server Plex e non sostituisce la gestione dei media.',
      'Si usas una biblioteca Plex, una lista central puede reunir tus fuentes. Cineradar ofrece una búsqueda web separada con país explícito. No se conecta a tu servidor Plex ni sustituye su gestión de archivos.',
      'If you already use a Plex library, one watchlist for different sources can be useful. Cineradar offers a separate web search with an explicit streaming country. It does not connect to your Plex server or replace its media management.',
    ),
    question: l(
      'Kann ich meine Plex-Watchlist in Cineradar synchronisieren?',
      'Puis-je synchroniser ma liste Plex avec Cineradar ?',
      'Posso sincronizzare la lista Plex con Cineradar?',
      '¿Puedo sincronizar mi lista Plex con Cineradar?',
      'Can I sync my Plex watchlist to Cineradar?',
    ),
    answer: l(
      'Derzeit nicht. Du kannst Titel einzeln auf Cineradar suchen und lokal speichern. Es gibt weder einen Plex-Import noch einen automatischen Abgleich. Deine vorhandenen Plex-Listen bleiben deshalb eigenständig.',
      'Pas actuellement. Vous pouvez chercher chaque titre et l’enregistrer localement. Il n’existe ni import Plex ni synchronisation automatique. Vos listes Plex restent séparées.',
      'Al momento no. Puoi cercare i titoli singolarmente e salvarli localmente. Non esiste importazione Plex né sincronizzazione automatica. Le liste Plex restano separate.',
      'Actualmente no. Puedes buscar títulos individualmente y guardarlos localmente. No hay importación de Plex ni sincronización automática. Tus listas Plex siguen separadas.',
      'Not currently. You can search titles individually and save them locally. There is no Plex import or automatic synchronization. Your existing Plex lists remain separate.',
    ),
    example: 'The Matrix Resurrections',
    related: ['trakt', 'playpilot', 'justwatch'],
  },
  {
    id: 'trakt',
    brand: 'Trakt',
    url: 'https://app.trakt.tv/',
    publishedAt: reviewed,
    updatedAt: reviewed,
    focus: l(
      'Serienfortschritt oder Angebotssuche?',
      'Suivre ses séries ou trouver une offre ?',
      'Seguire le serie o trovare un’offerta?',
      '¿Seguir series o encontrar ofertas?',
      'Track your series or find an offer?',
    ),
    intro: l(
      'Welche Folge fehlt noch, und wo lässt sie sich ansehen? Diese Fragen hängen zusammen, brauchen aber unterschiedliche Funktionen. Vergleiche Cineradar als Streaming-Suche mit Trakts Schwerpunkt auf deinem Sehverlauf.',
      'Quel épisode reste à voir et où le regarder ? Ces questions liées exigent des fonctions différentes. Comparez la recherche Cineradar à l’approche centrée sur votre historique de visionnage.',
      'Quale episodio manca e dove si può vedere? Sono domande collegate che richiedono funzioni diverse. Confronta la ricerca Cineradar con l’approccio alla cronologia di visione.',
      '¿Qué episodio te falta y dónde verlo? Son preguntas relacionadas que requieren funciones distintas. Compara la búsqueda de Cineradar con el enfoque en el historial de visionado.',
      'Which episode is next, and where can you watch it? These related questions need different features. Compare Cineradar’s streaming search with an approach centered on viewing history.',
    ),
    claims: [
      claim(
        'tracking',
        l(
          'Scrobbling erfasst Wiedergabeereignisse aus angebundenen Mediencentern.',
          'Le scrobbling enregistre la lecture depuis des lecteurs connectés.',
          'Lo scrobbling registra la riproduzione da lettori collegati.',
          'El scrobbling registra reproducciones desde centros multimedia conectados.',
          'Scrobbling records playback events from connected media centers.',
        ),
        'https://docs.trakt.tv/reference/about-scrobble',
      ),
      claim(
        'discover',
        l(
          'App-Ökosystem mit Integrationen und Scrobbling-Angeboten; Verfügbarkeit hängt von App und Tarif ab.',
          'Écosystème d’apps et intégrations ; disponibilité selon application et formule.',
          'Ecosistema di app e integrazioni; disponibilità secondo app e piano.',
          'Ecosistema de apps e integraciones; disponibilidad según app y plan.',
          'App ecosystem and integrations; availability depends on app and plan.',
        ),
        'https://media-og.trakt.tv/apps',
        web,
        'eingeschränkt',
      ),
    ],
    decision: l(
      'Wenn dein Ziel ein verlässlicher persönlicher Sehverlauf ist, bleibe bei einem dafür vorgesehenen Tracking-Werkzeug und prüfe dessen Integrationen. Cineradar ergänzt den nächsten Schritt: einen Film oder eine Serie im gewünschten Markt suchen. Staffelangebote sind keine Markierung dafür, welche Episoden du schon gesehen hast.',
      'Pour conserver votre historique personnel, choisissez un outil de suivi et vérifiez ses intégrations. Cineradar complète l’étape suivante : trouver un film ou une série dans le marché voulu. Une offre de saison n’indique pas les épisodes déjà vus.',
      'Per conservare la cronologia personale, scegli uno strumento di tracciamento e verifica le integrazioni. Cineradar completa il passo successivo: cercare un film o una serie nel mercato desiderato. Un’offerta di stagione non indica gli episodi già visti.',
      'Para conservar tu historial personal, elige una herramienta de seguimiento y revisa sus integraciones. Cineradar complementa el siguiente paso: encontrar una película o serie en tu mercado. Una oferta de temporada no indica qué episodios has visto.',
      'For a personal viewing history, use a tracking tool and check its integrations. Cineradar complements the next step: searching for a movie or series in your market. A season offer is not a record of which episodes you have watched.',
    ),
    question: l(
      'Kann Cineradar meinen Trakt-Verlauf übernehmen?',
      'Cineradar peut-il reprendre mon historique Trakt ?',
      'Cineradar può importare la cronologia Trakt?',
      '¿Cineradar puede importar mi historial de Trakt?',
      'Can Cineradar import my Trakt history?',
    ),
    answer: l(
      'Nein. Aktuell gibt es weder einen Trakt-Import noch Scrobbling oder Episodenfortschritt. Die lokale Merkliste speichert ausgewählte Titel und ihren Markt. Sie soll beim Wiederfinden helfen und ist kein Ersatz für ein Sehtagebuch.',
      'Non. Il n’y a actuellement ni import Trakt, ni scrobbling, ni progression par épisode. La liste locale conserve les titres choisis et leur marché. Elle sert à les retrouver, pas à tenir un journal de visionnage.',
      'No. Non ci sono importazione Trakt, scrobbling o progressi per episodio. La lista locale salva i titoli scelti e il mercato. Aiuta a ritrovarli, ma non sostituisce un diario di visione.',
      'No. Actualmente no hay importación de Trakt, scrobbling ni progreso por episodio. La lista local guarda títulos elegidos y su mercado. Sirve para recuperarlos, no para sustituir un diario de visionado.',
      'No. There is currently no Trakt import, scrobbling or episode progress. The local watchlist saves selected titles and their market. It helps you find them again; it does not replace a viewing diary.',
    ),
    example: 'Reacher',
    related: ['plex', 'wer-streamt-es', 'playpilot'],
  },
];
