import type { Locale } from '@/i18n/config';

const l = (
  de: string,
  fr: string,
  it: string,
  es: string,
  en: string,
): Record<Locale, string> => ({ de, fr, it, es, en });

export const analyticsCopy = {
  title: l(
    'Deine Privatsphäre. Deine Entscheidung.',
    'Votre vie privée, votre choix.',
    'La tua privacy, la tua scelta.',
    'Tu privacidad, tu decisión.',
    'Your privacy. Your choice.',
  ),
  intro: l(
    'Mit deiner Zustimmung hilft uns Google Analytics zu verstehen, welche Funktionen gut funktionieren und wo wir Cineradar verbessern können. Ohne Zustimmung bleibt die Statistik ausgeschaltet.',
    'Avec votre accord, Google Analytics nous aide à comprendre les fonctions utiles et à améliorer Cineradar. Sans votre accord, les statistiques restent désactivées.',
    'Con il tuo consenso, Google Analytics ci aiuta a capire quali funzioni sono utili e a migliorare Cineradar. Senza consenso, le statistiche restano disattivate.',
    'Con tu permiso, Google Analytics nos ayuda a entender qué funciones son útiles y a mejorar Cineradar. Sin tu consentimiento, las estadísticas permanecen desactivadas.',
    'With your permission, Google Analytics helps us understand which features work well and improve Cineradar. Analytics stays off unless you agree.',
  ),
  bannerIntro: l(
    'Mit deiner Zustimmung nutzen wir Google Analytics, um Cineradar zu verbessern. Du kannst die Seite auch ohne Statistik nutzen.',
    'Avec votre accord, Google Analytics nous aide à améliorer Cineradar. Le site reste accessible sans statistiques.',
    'Con il tuo consenso, Google Analytics ci aiuta a migliorare Cineradar. Puoi usare il sito anche senza statistiche.',
    'Con tu permiso, Google Analytics nos ayuda a mejorar Cineradar. Puedes usar la web sin estadísticas.',
    'With your permission, Google Analytics helps us improve Cineradar. You can use the site without analytics.',
  ),
  bannerStorage: l(
    'Auswahl für 180 Tage. Jederzeit im Footer änderbar.',
    'Choix conservé 180 jours, modifiable en bas de page.',
    'Scelta salvata per 180 giorni, modificabile a fondo pagina.',
    'Elección guardada 180 días. Puedes cambiarla al pie de página.',
    'Choice saved for 180 days. Change it anytime in the footer.',
  ),
  closeWithoutAnalytics: l(
    'Ohne Statistik schließen',
    'Fermer sans statistiques',
    'Chiudi senza statistiche',
    'Cerrar sin estadísticas',
    'Close without analytics',
  ),
  necessary: l(
    'Notwendige Funktionen',
    'Fonctions nécessaires',
    'Funzioni necessarie',
    'Funciones necesarias',
    'Necessary features',
  ),
  alwaysOn: l(
    'Immer aktiv',
    'Toujours actives',
    'Sempre attive',
    'Siempre activas',
    'Always on',
  ),
  statistics: l(
    'Statistik mit Google Analytics',
    'Statistiques avec Google Analytics',
    'Statistiche con Google Analytics',
    'Estadísticas con Google Analytics',
    'Statistics with Google Analytics',
  ),
  optional: l(
    'Optional',
    'Facultatives',
    'Facoltative',
    'Opcionales',
    'Optional',
  ),
  details: l(
    'Erfasst werden pseudonyme Nutzungs- und Gerätedaten, etwa Seitenaufrufe, Klicks und Funktionsereignisse. Keine Namen, E-Mail-Adressen, Formulartexte oder eingegebenen Suchbegriffe. Google verarbeitet Daten auch in den USA. Keine Werbepersonalisierung.',
    'Nous mesurons des données pseudonymes d’utilisation et d’appareil : pages vues, clics et interactions. Aucun nom, e-mail, contenu de formulaire ni terme de recherche saisi. Google traite aussi des données aux États-Unis. Pas de publicité personnalisée.',
    'Raccogliamo dati pseudonimi di utilizzo e dispositivo, come pagine viste, clic e interazioni. Nessun nome, indirizzo e-mail, testo dei moduli o ricerca digitata. Google tratta dati anche negli Stati Uniti. Nessuna personalizzazione pubblicitaria.',
    'Medimos datos seudónimos de uso y dispositivo, como páginas vistas, clics e interacciones. No enviamos nombres, correos, textos de formularios ni búsquedas escritas. Google también trata datos en Estados Unidos. Sin personalización publicitaria.',
    'We measure pseudonymous usage and device data, such as page views, clicks and feature interactions. No names, email addresses, form text or typed search queries. Google also processes data in the USA. No advertising personalization.',
  ),
  storage: l(
    'Deine Auswahl wird 180 Tage gespeichert. Du kannst sie jederzeit über „Datenschutzeinstellungen“ im Footer ändern.',
    'Votre choix est conservé 180 jours. Vous pouvez le modifier à tout moment via « Paramètres de confidentialité » en bas de page.',
    'La tua scelta viene conservata per 180 giorni. Puoi modificarla in qualsiasi momento tramite « Impostazioni privacy » a fondo pagina.',
    'Tu elección se guarda durante 180 días. Puedes cambiarla en cualquier momento en « Ajustes de privacidad », al pie de página.',
    'Your choice is stored for 180 days. You can change it at any time using “Privacy settings” in the footer.',
  ),
  accept: l('Akzeptieren', 'Accepter', 'Accetta', 'Aceptar', 'Accept'),
  decline: l('Ablehnen', 'Refuser', 'Rifiuta', 'Rechazar', 'Decline'),
  withdraw: l(
    'Einwilligung widerrufen',
    'Retirer mon consentement',
    'Revoca il consenso',
    'Retirar consentimiento',
    'Withdraw consent',
  ),
  allow: l(
    'Statistik erlauben',
    'Autoriser les statistiques',
    'Consenti le statistiche',
    'Permitir estadísticas',
    'Allow analytics',
  ),
  settings: l(
    'Datenschutzeinstellungen',
    'Paramètres de confidentialité',
    'Impostazioni privacy',
    'Ajustes de privacidad',
    'Privacy settings',
  ),
  more: l(
    'Details und Einstellungen',
    'Détails et paramètres',
    'Dettagli e impostazioni',
    'Detalles y ajustes',
    'Details and settings',
  ),
  privacy: l(
    'Datenschutz',
    'Confidentialité',
    'Privacy',
    'Privacidad',
    'Privacy policy',
  ),
  close: l('Schließen', 'Fermer', 'Chiudi', 'Cerrar', 'Close'),
  enabled: l(
    'Statistik ist aktiviert',
    'Les statistiques sont activées',
    'Le statistiche sono attive',
    'Las estadísticas están activadas',
    'Analytics is enabled',
  ),
  disabled: l(
    'Statistik ist ausgeschaltet',
    'Les statistiques sont désactivées',
    'Le statistiche sono disattivate',
    'Las estadísticas están desactivadas',
    'Analytics is off',
  ),
  noChoice: l(
    'Noch keine Auswahl getroffen',
    'Aucun choix enregistré',
    'Nessuna scelta registrata',
    'Aún no has elegido',
    'No choice recorded yet',
  ),
};

export const analyticsPrivacyCopy = {
  heading: l(
    'Optionale Nutzungsstatistik mit Google Analytics 4',
    'Statistiques facultatives avec Google Analytics 4',
    'Statistiche facoltative con Google Analytics 4',
    'Estadísticas opcionales con Google Analytics 4',
    'Optional usage analytics with Google Analytics 4',
  ),
  consent: l(
    'Wir verwenden Google Analytics 4 erst nach deiner ausdrücklichen Einwilligung. Ohne Zustimmung laden wir das Analytics-Skript nicht und senden keine Analytics-Ereignisse. Die Suche, Merkliste und übrigen Funktionen kannst du auch ohne Statistik nutzen.',
    'Google Analytics 4 est utilisé uniquement après votre consentement explicite. Sans accord, nous ne chargeons pas le script Analytics et n’envoyons aucun événement Analytics. La recherche, la liste et les autres fonctions restent disponibles.',
    'Utilizziamo Google Analytics 4 solo dopo il tuo consenso esplicito. Senza consenso non carichiamo lo script Analytics e non inviamo eventi Analytics. Ricerca, lista e altre funzioni restano disponibili.',
    'Usamos Google Analytics 4 solo con tu consentimiento explícito. Sin él, no cargamos su script ni enviamos eventos Analytics. Puedes usar la búsqueda, la lista y las demás funciones sin estadísticas.',
    'We use Google Analytics 4 only after your explicit consent. Without consent, we do not load the Analytics script or send Analytics events. Search, your watchlist and other features remain available without analytics.',
  ),
  data: l(
    'Die Statistik umfasst pseudonyme Cookie-Kennungen, technische Browser- und Gerätedaten sowie Nutzungsereignisse: Seitenaufrufe, Klicks, Scrolltiefe, Suchergebniszahlen, Filter, Ladeergebnisse, Merklistenaktionen und Aufrufe von Streaminganbietern. Sprache, Streaming-Land und öffentliche Titel- oder Anbieterkennungen helfen, diese Ereignisse einzuordnen. Namen, E-Mail-Adressen, Formularinhalte und eingegebene Suchbegriffe werden nicht an Google Analytics übermittelt. Werbepersonalisierung und Google Signals sind für unsere Messung deaktiviert.',
    'Les statistiques comprennent des identifiants de cookies pseudonymes, des données techniques de navigateur et d’appareil et des événements : pages vues, clics, défilement, nombre de résultats, filtres, chargements, actions sur la liste et accès aux plateformes. La langue, le pays de streaming et les identifiants publics de titres ou plateformes apportent du contexte. Noms, e-mails, formulaires et recherches saisies ne sont pas transmis à Google Analytics. Personnalisation publicitaire et Google Signals sont désactivés pour notre mesure.',
    'Le statistiche comprendono identificativi cookie pseudonimi, dati tecnici di browser e dispositivo ed eventi: pagine viste, clic, scorrimento, numero di risultati, filtri, caricamenti, azioni sulla lista e accessi alle piattaforme. Lingua, paese di streaming e identificativi pubblici di titoli o piattaforme forniscono contesto. Nomi, e-mail, contenuti dei moduli e ricerche digitate non vengono trasmessi a Google Analytics. Personalizzazione pubblicitaria e Google Signals sono disattivati per la nostra misurazione.',
    'Las estadísticas incluyen identificadores de cookies seudónimos, datos técnicos de navegador y dispositivo y eventos: páginas vistas, clics, desplazamiento, número de resultados, filtros, cargas, acciones de la lista y accesos a plataformas. El idioma, el país de streaming y los identificadores públicos de títulos o plataformas aportan contexto. No enviamos nombres, correos, contenidos de formularios ni búsquedas escritas a Google Analytics. La personalización publicitaria y Google Signals están desactivados para nuestra medición.',
    'Analytics includes pseudonymous cookie identifiers, technical browser and device data and usage events: page views, clicks, scroll depth, result counts, filters, loading outcomes, watchlist actions and visits to streaming providers. Language, streaming country and public title or provider identifiers give these events context. Names, email addresses, form contents and typed search queries are not sent to Google Analytics. Advertising personalization and Google Signals are disabled for our measurement.',
  ),
  provider: l(
    'Google Analytics ist ein Dienst von Google. In Europa ist Google Ireland Limited, Irland, zuständig. Google kann Daten auch auf Servern in den USA verarbeiten. Weitere Informationen zur Datenverarbeitung und internationalen Übermittlung findest du in den unten verlinkten Datenschutzhinweisen von Google.',
    'Google Analytics est un service de Google. Google Ireland Limited, en Irlande, est compétente en Europe. Google peut également traiter des données sur des serveurs aux États-Unis. Consultez les informations de confidentialité de Google ci-dessous pour le traitement et les transferts internationaux.',
    'Google Analytics è un servizio Google. In Europa è competente Google Ireland Limited, Irlanda. Google può trattare dati anche su server negli Stati Uniti. Consulta le informazioni sulla privacy di Google qui sotto per il trattamento e i trasferimenti internazionali.',
    'Google Analytics es un servicio de Google. En Europa corresponde a Google Ireland Limited, Irlanda. Google también puede tratar datos en servidores de Estados Unidos. Consulta los avisos de privacidad de Google enlazados para conocer el tratamiento y las transferencias internacionales.',
    'Google Analytics is a Google service. Google Ireland Limited, Ireland, is responsible in Europe. Google may also process data on servers in the USA. See the linked Google privacy information for details of processing and international transfers.',
  ),
  cookies: l(
    'Deine Entscheidung speichern wir für 180 Tage in einer notwendigen Einstellung. Nach Zustimmung werden Analytics-Cookies wie _ga mit einer Laufzeit von 180 Tagen gesetzt. Die Ereignisaufbewahrung ist auf 14 Monate eingestellt. Bei Nutzerkennungen verlängert neue Aktivität diese Frist. Aggregierte Berichte sind von dieser Begrenzung ausgenommen.',
    'Votre choix est conservé 180 jours dans un paramètre nécessaire. Après accord, des cookies Analytics tels que _ga sont définis avec une durée de 180 jours. Les événements sont conservés 14 mois. Une nouvelle activité prolonge ce délai pour les identifiants utilisateurs. Cette limite ne concerne pas les rapports agrégés.',
    'Conserviamo la scelta per 180 giorni in un’impostazione necessaria. Dopo il consenso, cookie Analytics come _ga hanno una durata di 180 giorni. Gli eventi vengono conservati per 14 mesi. Nuove attività prolungano questo termine per gli identificativi utente. Il limite non riguarda i rapporti aggregati.',
    'Guardamos tu decisión durante 180 días en un ajuste necesario. Tras aceptar, las cookies Analytics como _ga se configuran con una duración de 180 días. Los eventos se conservan 14 meses. La nueva actividad amplía este plazo para los identificadores de usuario. El límite no afecta a los informes agregados.',
    'Your choice is stored for 180 days as a necessary preference. After consent, Analytics cookies such as _ga are set with a 180-day lifetime. Event retention is set to 14 months. New activity extends retention of user identifiers. This limit does not apply to aggregated reports.',
  ),
  withdrawal: l(
    'Du kannst deine Einwilligung jederzeit über „Datenschutzeinstellungen“ im Footer widerrufen. Dann stoppen neue Analytics-Ereignisse und wir entfernen die erreichbaren Analytics-Cookies dieser Website. Der Widerruf gilt für die Zukunft; bereits übermittelte Daten werden dadurch nicht automatisch bei Google gelöscht.',
    'Vous pouvez retirer votre consentement à tout moment via « Paramètres de confidentialité » en bas de page. Les nouveaux événements Analytics cessent et nous supprimons les cookies Analytics accessibles du site. Le retrait vaut pour l’avenir ; il n’efface pas automatiquement les données déjà transmises à Google.',
    'Puoi revocare il consenso in qualsiasi momento tramite « Impostazioni privacy » a fondo pagina. L’invio di nuovi eventi Analytics si interrompe e rimuoviamo i cookie Analytics accessibili del sito. La revoca vale per il futuro e non elimina automaticamente i dati già trasmessi a Google.',
    'Puedes retirar tu consentimiento en « Ajustes de privacidad », al pie de página. Dejamos de enviar nuevos eventos Analytics y eliminamos las cookies Analytics accesibles del sitio. La retirada se aplica al futuro y no borra automáticamente los datos ya enviados a Google.',
    'You can withdraw consent at any time using “Privacy settings” in the footer. New Analytics events stop and we remove this website’s accessible Analytics cookies. Withdrawal applies going forward; it does not automatically delete data already sent to Google.',
  ),
};
