import { l } from './comparisons/copy';

export const calendarCopy = {
  title: l(
    'Serienkalender: neue Folgen & Sendetermine',
    'Calendrier des séries : épisodes et diffusions',
    'Calendario serie: nuovi episodi e uscite',
    'Calendario de series: episodios y estrenos',
    'Series calendar: new episodes & air dates',
  ),
  intro: l(
    'Deine nächsten Serienabende, auf einen Blick. Entdecke angekündigte Folgen und Staffelstarts der kommenden 14 Tage.',
    'Vos prochaines soirées séries, en un coup d’œil. Découvrez les épisodes et débuts de saison annoncés pour les 14 prochains jours.',
    'Le tue prossime serate serie, a colpo d’occhio. Scopri episodi e inizi di stagione annunciati per i prossimi 14 giorni.',
    'Tus próximas noches de series, de un vistazo. Descubre episodios e inicios de temporada anunciados para los próximos 14 días.',
    'Your next series nights, at a glance. Discover episodes and season premieres announced for the next 14 days.',
  ),
  metaTitle: l(
    'Serienkalender: neue Folgen & Sendetermine',
    'Calendrier des séries : épisodes et dates',
    'Calendario serie: nuovi episodi e uscite',
    'Calendario de series: episodios y estrenos',
    'Series calendar: new episodes & air dates',
  ),
  metaDescription: l(
    'Wann kommt die nächste Folge? Finde angekündigte Serienfolgen und Staffelstarts für die nächsten 14 Tage, mit Original-Sendeterminen und Episodeninfos.',
    'Quand sort le prochain épisode ? Retrouvez les épisodes et débuts de saison annoncés sur 14 jours, avec dates de diffusion originale et infos des épisodes.',
    'Quando esce il prossimo episodio? Trova episodi e inizi di stagione annunciati nei prossimi 14 giorni, con date di prima trasmissione e dettagli.',
    '¿Cuándo sale el próximo episodio? Consulta episodios e inicios de temporada anunciados en los próximos 14 días, con fechas de emisión original y detalles.',
    'When is the next episode? Find episodes and season premieres announced for the next 14 days, with original air dates and episode details.',
  ),
  today: l('Heute', 'Aujourd’hui', 'Oggi', 'Hoy', 'Today'),
  tomorrow: l('Morgen', 'Demain', 'Domani', 'Mañana', 'Tomorrow'),
  schedule: l(
    'Die nächsten 14 Tage',
    'Les 14 prochains jours',
    'I prossimi 14 giorni',
    'Los próximos 14 días',
    'The next 14 days',
  ),
  episodeCount: l('Termine', 'Diffusions', 'Uscite', 'Emisiones', 'Air dates'),
  episodeSingular: l('Termin', 'Diffusion', 'Uscita', 'Emisión', 'Air date'),
  dayNavigation: l(
    'Zum Sendetag springen',
    'Aller à un jour de diffusion',
    'Vai a un giorno di uscita',
    'Ir a un día de emisión',
    'Jump to an air date',
  ),
  premiere: l(
    'Staffelstart',
    'Début de saison',
    'Inizio stagione',
    'Inicio de temporada',
    'Season premiere',
  ),
  discoverSeries: l(
    'Serien entdecken',
    'Découvrir des séries',
    'Scopri le serie',
    'Descubrir series',
    'Discover series',
  ),
  editorialHeading: l(
    'Neue Serienfolgen planen, Lieblingsserien weitersehen',
    'Préparez vos prochaines soirées séries',
    'Organizza le tue serate con i nuovi episodi',
    'Organiza tus próximas noches de series',
    'Plan your next episode night',
  ),
  editorialIntro: l(
    'Eine Woche bis zur nächsten Folge oder schon heute Abend weitersehen? Der Cineradar-Serienkalender ordnet angekündigte Episoden nach Sendetag. So findest du neue Folgen deiner Lieblingsserien und entdeckst Serienstarts oder neue Staffeln, wenn deren erste Folge im Zeitraum liegt. Die Auswahl umfasst angekündigte Folgen der kommenden 14 Tage.',
    'Le prochain épisode arrive-t-il ce soir ou la semaine prochaine ? Le calendrier Cineradar classe les épisodes annoncés par jour de diffusion. Retrouvez vos séries et repérez les nouvelles séries ou saisons dont le premier épisode tombe dans la période. La sélection couvre les épisodes annoncés pour les 14 prochains jours.',
    'Il prossimo episodio arriva stasera o la settimana prossima? Il calendario Cineradar ordina gli episodi annunciati per giorno di uscita. Segui le tue serie e scopri nuove serie o stagioni quando il loro primo episodio rientra nel periodo. La selezione comprende gli episodi annunciati per i prossimi 14 giorni.',
    '¿El próximo episodio llega esta noche o la semana que viene? El calendario de Cineradar organiza los episodios anunciados por día de emisión. Sigue tus series y descubre estrenos de series o temporadas cuando su primer episodio cae dentro del periodo. La selección abarca los episodios anunciados para los próximos 14 días.',
    'Is the next episode coming tonight or next week? The Cineradar series calendar groups announced episodes by air date. Follow returning series and spot new series or season premieres when their first episode falls within the schedule. The selection covers episodes announced for the next 14 days.',
  ),
  howHeading: l(
    'Von der nächsten Folge zum Episodenführer',
    'Du prochain épisode au guide de la série',
    'Dal prossimo episodio alla guida della serie',
    'Del próximo episodio a la guía de la serie',
    'From the next episode to the series guide',
  ),
  howText: l(
    'Wähle einen Tag und vergleiche Serientitel, Staffel- und Folgennummer sowie die angekündigte Uhrzeit. Ein markierter Staffelstart gehört zur ersten regulären Folge einer Staffel. Bei verlinkten Titeln führt dich ein Klick zur Serienseite auf Cineradar: Dort findest du weitere Informationen und, sofern vorhanden, den Episodenführer sowie passende Streamingangebote.',
    'Choisissez un jour pour consulter le titre de la série, le numéro de saison et d’épisode et l’horaire annoncé. La mention « Début de saison » désigne le premier épisode régulier d’une saison. Les titres cliquables ouvrent leur fiche Cineradar, avec des informations complémentaires et, lorsqu’ils sont disponibles, un guide des épisodes et les offres de streaming.',
    'Scegli un giorno per consultare il titolo della serie, il numero di stagione ed episodio e l’orario annunciato. L’etichetta « Inizio stagione » indica il primo episodio regolare di una stagione. I titoli con un collegamento aprono la scheda Cineradar, dove trovi altre informazioni e, quando disponibili, la guida agli episodi e le offerte streaming.',
    'Elige un día para consultar el título de la serie, los números de temporada y episodio y la hora anunciada. La etiqueta « Inicio de temporada » señala el primer episodio regular de una temporada. Los títulos con enlace abren su ficha en Cineradar, con más información y, cuando están disponibles, una guía de episodios y ofertas de streaming.',
    'Choose a day to check the series title, season and episode numbers, and announced time. A season premiere label marks the first regular episode of a season. Linked titles open their Cineradar series page, where you can find more information and, when available, an episode guide and streaming offers.',
  ),
  availabilityHeading: l(
    'Sendetermin und Streamingstart richtig einordnen',
    'Distinguer diffusion et disponibilité en streaming',
    'Distinguere la prima uscita dalla disponibilità streaming',
    'Distinguir emisión original y disponibilidad en streaming',
    'Understand air dates and streaming availability',
  ),
  availabilityText: l(
    'Der Kalender zeigt Originalausstrahlungen im Fernsehen und gemeldete Termine von Streamingkanälen. Bekannte Uhrzeiten werden in die angezeigte Zeitzone umgerechnet. Ein Termin im Ursprungsland bedeutet deshalb nicht automatisch, dass die Folge gleichzeitig bei deinem Streaminganbieter verfügbar ist. Die Angebote auf der Serienseite beziehen sich auf die Serie im ausgewählten Land; einzelne Staffeln und Folgen können später erscheinen.',
    'Le calendrier présente les diffusions originales à la télévision et les dates annoncées par les plateformes de streaming. Les horaires connus sont convertis dans le fuseau indiqué. Une diffusion dans le pays d’origine ne garantit donc pas la disponibilité simultanée de l’épisode sur votre plateforme. Les offres de la fiche concernent la série dans le pays sélectionné ; certaines saisons ou certains épisodes peuvent arriver plus tard.',
    'Il calendario mostra le prime trasmissioni televisive e le date segnalate per i canali streaming. Gli orari noti vengono convertiti nel fuso indicato. L’uscita nel paese d’origine non garantisce quindi che l’episodio sia subito disponibile sulla tua piattaforma. Le offerte nella scheda riguardano la serie nel paese selezionato; singole stagioni ed episodi possono arrivare più tardi.',
    'El calendario muestra emisiones originales de televisión y fechas anunciadas por canales de streaming. Las horas conocidas se convierten a la zona horaria indicada. Una emisión en el país de origen no garantiza que el episodio esté disponible a la vez en tu plataforma. Las ofertas de la ficha corresponden a la serie en el país seleccionado; algunas temporadas y episodios pueden llegar más tarde.',
    'The calendar shows original television broadcasts and reported dates for streaming channels. Known times are converted to the displayed time zone. An episode airing in its home country does not guarantee that it is available on your streaming service at the same time. Offers on the series page refer to the series in your selected country; individual seasons and episodes may arrive later.',
  ),
  faqHeading: l(
    'Fragen zum Serienkalender',
    'Questions sur le calendrier des séries',
    'Domande sul calendario delle serie',
    'Preguntas sobre el calendario de series',
    'Series calendar questions',
  ),
  faqs: [
    {
      question: l(
        'Wann kommt die nächste Folge meiner Serie?',
        'Quand sort le prochain épisode de ma série ?',
        'Quando esce il prossimo episodio della mia serie?',
        '¿Cuándo sale el próximo episodio de mi serie?',
        'When does the next episode of my series come out?',
      ),
      answer: l(
        'Suche den Serientitel im Kalender nach Sendetag. Angezeigte Termine liegen innerhalb der nächsten 14 Tage. Bei verlinkten Serien kannst du den Episodenführer auf der Titelseite öffnen. Fehlt eine Folge, kann ihr Termin noch offen sein, außerhalb des Zeitraums liegen oder noch nicht in unseren Daten stehen.',
        'Consultez les jours de diffusion dans le calendrier pour retrouver votre série. Les dates affichées se situent dans les 14 prochains jours. Pour les séries avec un lien, la fiche donne accès au guide des épisodes. Un épisode absent peut ne pas encore avoir de date, se situer hors de la période ou manquer dans nos données.',
        'Cerca la serie tra i giorni del calendario. Le date mostrate rientrano nei prossimi 14 giorni. Per le serie con un collegamento puoi aprire la guida agli episodi dalla scheda. Un episodio assente potrebbe non avere ancora una data, uscire fuori dal periodo o non essere presente nei nostri dati.',
        'Busca la serie entre los días del calendario. Las fechas mostradas corresponden a los próximos 14 días. En las series con enlace puedes abrir la guía de episodios desde su ficha. Si falta un episodio, puede que aún no tenga fecha, quede fuera del periodo o todavía no figure en nuestros datos.',
        'Look for the series under its air date in the calendar. Listed dates fall within the next 14 days. Linked series let you open the episode guide on their title page. A missing episode may not have an announced date, may fall outside the schedule, or may not yet be in our data.',
      ),
    },
    {
      question: l(
        'Zeigt der Serienkalender auch neue Staffeln und Serienstarts?',
        'Le calendrier indique-t-il les nouvelles séries et saisons ?',
        'Il calendario mostra anche nuove serie e stagioni?',
        '¿El calendario incluye estrenos de series y temporadas?',
        'Does the calendar include new series and season premieres?',
      ),
      answer: l(
        'Ja, wenn die erste reguläre Folge einer Staffel für den gezeigten Zeitraum angekündigt und erfasst ist. Sie ist als Staffelstart markiert. Staffel 1 kann einen Serienstart anzeigen; höhere Staffelnummern kennzeichnen die Rückkehr einer Serie. Unangekündigte Starttermine und vollständige Staffelveröffentlichungen werden nicht daraus abgeleitet.',
        'Oui, lorsque le premier épisode régulier d’une saison est annoncé et présent dans les données pour la période affichée. Il porte la mention « Début de saison ». La saison 1 peut correspondre au lancement d’une série, les suivantes à son retour. Cela ne permet pas de déduire une date non annoncée ni la sortie d’une saison entière.',
        'Sì, quando il primo episodio regolare di una stagione è annunciato e presente nei dati per il periodo mostrato. È indicato come « Inizio stagione ». La stagione 1 può segnare il debutto di una serie, le successive il suo ritorno. Non vengono dedotte date non annunciate né uscite di intere stagioni.',
        'Sí, cuando el primer episodio regular de una temporada está anunciado y registrado para el periodo mostrado. Lleva la etiqueta « Inicio de temporada ». La temporada 1 puede indicar el estreno de una serie; las siguientes, su regreso. Esto no permite deducir fechas sin anunciar ni la publicación de temporadas completas.',
        'Yes, when a season’s first regular episode has an announced date within the displayed schedule and is in our data. It carries a season premiere label. Season 1 may mark a series debut; higher season numbers indicate a returning series. We do not infer unannounced dates or full-season releases from an episode premiere.',
      ),
    },
    {
      question: l(
        'Kann ich die Folge am Sendetermin in meinem Land streamen?',
        'Puis-je regarder l’épisode en streaming à cette date dans mon pays ?',
        'Posso guardare l’episodio in streaming quel giorno nel mio paese?',
        '¿Puedo ver el episodio en streaming ese día en mi país?',
        'Can I stream the episode in my country on its air date?',
      ),
      answer: l(
        'Nicht unbedingt. Der Termin kann sich auf die Originalausstrahlung in einem anderen Land beziehen. Auch ein internationaler Sendetermin sagt noch nichts über jede Sprachfassung oder Region aus. Öffne die Serienseite und prüfe das Angebot für dein ausgewähltes Land. Staffelumfang und einzelne Folgen können sich je Anbieter unterscheiden.',
        'Pas nécessairement. La date peut correspondre à la diffusion originale dans un autre pays. Même une diffusion internationale ne garantit pas toutes les langues ni toutes les régions. Consultez la fiche de la série et les offres pour le pays sélectionné. Les saisons et épisodes disponibles peuvent varier selon la plateforme.',
        'Non necessariamente. La data può riferirsi alla prima trasmissione in un altro paese. Anche una data di uscita internazionale non garantisce tutte le lingue o le regioni. Apri la scheda della serie e controlla le offerte per il paese selezionato. Stagioni ed episodi disponibili possono variare tra le piattaforme.',
        'No necesariamente. La fecha puede corresponder a la emisión original en otro país. Una fecha de emisión internacional tampoco garantiza todos los idiomas o regiones. Abre la ficha de la serie y consulta las ofertas para el país seleccionado. Las temporadas y los episodios disponibles pueden variar según la plataforma.',
        'Not necessarily. The date may refer to an original broadcast in another country. An international air date also does not guarantee every language or region. Open the series page and check offers for your selected country. Available seasons and individual episodes can vary by provider.',
      ),
    },
  ],
};
