import { l } from './comparisons/copy';
export const contactCopy = {
  intro: l(
    'Eine Frage zu Cineradar oder ein Angebot, das nicht stimmt? Beschreibe dein Anliegen möglichst konkret. So lässt sich deine Nachricht richtig zuordnen.',
    'Une question sur Cineradar ou une offre incorrecte ? Décrivez précisément votre demande pour faciliter son traitement.',
    'Una domanda su Cineradar o un’offerta errata? Descrivi con precisione il problema per facilitarne la gestione.',
    '¿Una pregunta sobre Cineradar o una oferta incorrecta? Describe tu consulta con precisión para facilitar su gestión.',
    'A question about Cineradar or an incorrect offer? Describe your request clearly so it can be directed appropriately.',
  ),
  name: l(
    'Vollständiger Name',
    'Nom complet',
    'Nome completo',
    'Nombre completo',
    'Full name',
  ),
  email: l(
    'E-Mail-Adresse',
    'Adresse e-mail',
    'Indirizzo e-mail',
    'Correo electrónico',
    'Email address',
  ),
  subject: l('Betreff', 'Objet', 'Oggetto', 'Asunto', 'Subject'),
  required: l(
    'Alle mit * markierten Felder sind Pflichtfelder.',
    'Tous les champs marqués * sont obligatoires.',
    'Tutti i campi con * sono obbligatori.',
    'Todos los campos con * son obligatorios.',
    'Fields marked * are required.',
  ),
  formTitle: l(
    'Deine Nachricht',
    'Votre message',
    'Il tuo messaggio',
    'Tu mensaje',
    'Your message',
  ),
  details: l(
    'Bei einem Datenfehler helfen Titel, Streaming-Land, Anbieter und der Link zur betroffenen Seite. Bitte sende keine Passwörter oder Zahlungsdaten.',
    'Pour une erreur, indiquez titre, pays, plateforme et lien concerné. N’envoyez ni mot de passe ni données de paiement.',
    'Per un errore indica titolo, paese, piattaforma e link. Non inviare password o dati di pagamento.',
    'Para un error indica título, país, plataforma y enlace. No envíes contraseñas ni datos de pago.',
    'For data errors, include the title, streaming country, provider and page link. Do not send passwords or payment details.',
  ),
  privacy: l(
    'Wir speichern Name, E-Mail, Betreff und Nachricht zur Bearbeitung deiner Anfrage. Weitere Informationen findest du in unserer',
    'Nous conservons nom, e-mail, objet et message pour traiter votre demande. Pour en savoir plus, consultez notre',
    'Conserviamo nome, e-mail, oggetto e messaggio per gestire la richiesta. Per i dettagli consulta la nostra',
    'Guardamos nombre, correo, asunto y mensaje para gestionar tu solicitud. Consulta más información en nuestra',
    'We store your name, email, subject and message to handle your request. Read more in our',
  ),
  service: l(
    'Fragen zur Nutzung',
    'Questions d’utilisation',
    'Domande sull’utilizzo',
    'Preguntas de uso',
    'Using Cineradar',
  ),
  help: l(
    'Antworten zu Anbietern, Zusatzkanälen, Ländern und Merklisten findest du in der Hilfe.',
    'Consultez l’aide pour les plateformes, chaînes supplémentaires, pays et listes.',
    'Consulta l’aiuto per piattaforme, canali aggiuntivi, paesi e liste.',
    'Consulta la ayuda sobre plataformas, canales adicionales, países y listas.',
    'Visit help for providers, add-on channels, countries and watchlists.',
  ),
  provider: l(
    'Fragen zu deinem Streaming-Abo',
    'Questions sur votre abonnement',
    'Domande sul tuo abbonamento',
    'Preguntas sobre tu suscripción',
    'Your streaming subscription',
  ),
  providerText: l(
    'Wiedergabe, Abrechnung und Kündigung bearbeitet dein Streaminganbieter. Cineradar hat keinen Zugriff auf dein dortiges Konto.',
    'Lecture, facturation et résiliation relèvent de votre plateforme. Cineradar n’a pas accès à votre compte chez elle.',
    'Riproduzione, fatturazione e disdetta competono alla piattaforma. Cineradar non ha accesso al tuo account presso di essa.',
    'Reproducción, facturación y cancelaciones corresponden a tu plataforma. Cineradar no tiene acceso a tu cuenta allí.',
    'Playback, billing and cancellations are handled by your streaming provider. Cineradar cannot access your account with that service.',
  ),
  operator: l(
    'Verantwortlicher Betreiber',
    'Exploitant responsable',
    'Gestore responsabile',
    'Operador responsable',
    'Responsible operator',
  ),
  stored: l(
    'Deine Nachricht wurde gespeichert. Die automatische E-Mail-Bestätigung ist derzeit noch nicht eingerichtet.',
    'Votre message a été enregistré. La confirmation automatique par e-mail n’est pas encore configurée.',
    'Il messaggio è stato salvato. La conferma automatica via e-mail non è ancora configurata.',
    'Tu mensaje se ha guardado. La confirmación automática por correo aún no está configurada.',
    'Your message has been saved. Automatic email confirmation is not yet configured.',
  ),
};
