import { l } from './comparisons/copy';

export const episodeCopy = {
  title: l(
    'Serienkalender',
    'Calendrier des séries',
    'Calendario delle serie',
    'Calendario de series',
    'Series calendar',
  ),
  intro: l(
    'Neue Folgen, nächste Staffeln und ihre angekündigten Sendetermine: dein Überblick für die kommenden 14 Tage.',
    'Nouveaux épisodes, prochaines saisons et dates annoncées : votre aperçu des 14 prochains jours.',
    'Nuovi episodi, prossime stagioni e date annunciate: la guida ai prossimi 14 giorni.',
    'Nuevos episodios, próximas temporadas y fechas anunciadas: tu guía de los próximos 14 días.',
    'New episodes, upcoming seasons and announced air dates: your guide to the next 14 days.',
  ),
  guide: l(
    'Folgen & Termine',
    'Épisodes et dates',
    'Episodi e date',
    'Episodios y fechas',
    'Episodes & air dates',
  ),
  next: l(
    'Wann kommt die nächste Folge?',
    'Quand sort le prochain épisode ?',
    'Quando esce il prossimo episodio?',
    '¿Cuándo sale el próximo episodio?',
    'When is the next episode?',
  ),
  none: l(
    'Noch kein weiterer Termin angekündigt.',
    'Aucune autre date annoncée.',
    'Nessun’altra data annunciata.',
    'No hay más fechas anunciadas.',
    'No further air date announced.',
  ),
  empty: l(
    'Für die kommenden 14 Tage liegen noch keine Sendetermine vor.',
    'Aucune date disponible pour les 14 prochains jours.',
    'Non ci sono ancora date per i prossimi 14 giorni.',
    'Todavía no hay fechas para los próximos 14 días.',
    'No air dates are available for the next 14 days yet.',
  ),
  tba: l(
    'Termin offen',
    'Date à confirmer',
    'Data da confermare',
    'Fecha por confirmar',
    'Date to be announced',
  ),
  original: l(
    'Originalausstrahlung',
    'Diffusion originale',
    'Prima trasmissione',
    'Emisión original',
    'Original broadcast',
  ),
  global: l(
    'Internationaler Streamingstart',
    'Première en streaming internationale',
    'Prima streaming internazionale',
    'Estreno internacional en streaming',
    'International streaming premiere',
  ),
  scope: l(
    'Die Termine beziehen sich auf die Originalausstrahlung. Streamingangebote auf der Serienseite zeigen die Verfügbarkeit der Serie; einzelne Folgen können abweichen.',
    'Les dates concernent la diffusion originale. Les offres indiquent la disponibilité de la série ; celle des épisodes peut varier.',
    'Le date si riferiscono alla prima trasmissione. Le offerte indicano la disponibilità della serie; i singoli episodi possono variare.',
    'Las fechas corresponden a la emisión original. Las ofertas indican la disponibilidad de la serie; los episodios pueden variar.',
    'Dates refer to the original broadcast. Streaming offers show series availability; individual episodes may differ.',
  ),
  source: l(
    'Episodendaten',
    'Données des épisodes',
    'Dati degli episodi',
    'Datos de episodios',
    'Episode data',
  ),
  adapted: l(
    'Daten normalisiert; Beschreibungen als Klartext.',
    'Données normalisées ; résumés en texte brut.',
    'Dati normalizzati; descrizioni in testo semplice.',
    'Datos normalizados; descripciones en texto plano.',
    'Data normalized; summaries converted to plain text.',
  ),
  more: l(
    'Vollständiger Episodenführer bei TVmaze',
    'Guide complet sur TVmaze',
    'Guida completa su TVmaze',
    'Guía completa en TVmaze',
    'Full episode guide on TVmaze',
  ),
  specials: l(
    'Specials',
    'Épisodes spéciaux',
    'Episodi speciali',
    'Especiales',
    'Specials',
  ),
  times: l(
    'Zeitzone',
    'Fuseau horaire',
    'Fuso orario',
    'Zona horaria',
    'Time zone',
  ),
  ratings: l(
    'Weitere Bewertungen',
    'Autres notes',
    'Altre valutazioni',
    'Otras valoraciones',
    'More ratings',
  ),
  awards: l('Auszeichnungen', 'Récompenses', 'Premi', 'Premios', 'Awards'),
  complete: l(
    'Alle Termine entdecken',
    'Voir toutes les dates',
    'Scopri tutte le date',
    'Ver todas las fechas',
    'Explore all air dates',
  ),
};

export const calendarZones: Record<string, string> = {
  de: 'Europe/Berlin',
  fr: 'Europe/Paris',
  it: 'Europe/Rome',
  es: 'Europe/Madrid',
  us: 'America/New_York',
};
