import { l } from './comparisons/copy';
export const infoDescriptions = {
  about: l(
    'Cineradar hilft dir, Filme und Serien bei Streamingdiensten zu finden. Erfahre, wer die Seite betreibt, wie die Suche funktioniert und wo ihre Grenzen liegen.',
    'Cineradar aide à trouver films et séries sur les plateformes. Découvrez son exploitant, le fonctionnement de la recherche et ses limites.',
    'Cineradar aiuta a trovare film e serie sulle piattaforme. Scopri chi lo gestisce, come funziona la ricerca e quali sono i limiti.',
    'Cineradar ayuda a encontrar películas y series en plataformas. Conoce quién lo opera, cómo funciona la búsqueda y sus límites.',
    'Cineradar helps you find movies and series on streaming services. Learn who operates it, how search works and what its limits are.',
  ),
  data: l(
    'So verarbeitet Cineradar Informationen von TMDB und der Streaming Availability API. Erfahre, was Länder, Prüfzeitpunkte, fehlende Angebote und Zusatzkanäle bedeuten.',
    'Comment Cineradar utilise TMDB et Streaming Availability API : pays, dates de vérification, offres manquantes et chaînes supplémentaires.',
    'Come Cineradar usa TMDB e Streaming Availability API: paesi, date di verifica, offerte mancanti e canali aggiuntivi.',
    'Cómo usa Cineradar TMDB y Streaming Availability API: países, fechas de comprobación, ofertas ausentes y canales adicionales.',
    'How Cineradar uses TMDB and Streaming Availability API: countries, check times, missing offers and add-on channels explained.',
  ),
  help: l(
    'Hilfe zur Cineradar-Suche: Streaming-Land ändern, Angebote unterscheiden, Merkliste nutzen und Datenfehler melden.',
    'Aide Cineradar : changer de pays, comprendre les offres, utiliser la liste à voir et signaler une erreur.',
    'Aiuto Cineradar: cambiare paese, capire le offerte, usare la lista e segnalare errori.',
    'Ayuda de Cineradar: cambiar país, entender ofertas, usar la lista y comunicar errores.',
    'Cineradar help: change your streaming country, understand offers, use your watchlist and report errors.',
  ),
  contact: l(
    'Kontaktiere Cineradar bei Fragen zur Website oder fehlerhaften Streamingdaten. Sende dein Anliegen mit Name, E-Mail-Adresse, Betreff und Nachricht.',
    'Contactez Cineradar pour une question ou une erreur de données. Envoyez nom, e-mail, objet et message.',
    'Contatta Cineradar per domande o dati errati. Invia nome, e-mail, oggetto e messaggio.',
    'Contacta con Cineradar por consultas o datos incorrectos. Envía nombre, correo, asunto y mensaje.',
    'Contact Cineradar about the website or incorrect streaming data. Submit your name, email, subject and message.',
  ),
  report: l(
    'Melde einen falschen Titel, einen defekten Anbieterlink oder unzutreffende Streamingangebote an Cineradar.',
    'Signalez un titre incorrect, un lien défectueux ou une offre erronée à Cineradar.',
    'Segnala un titolo errato, un link non funzionante o un’offerta inesatta a Cineradar.',
    'Informa a Cineradar de títulos incorrectos, enlaces rotos u ofertas erróneas.',
    'Report an incorrect title, broken provider link or inaccurate streaming offer to Cineradar.',
  ),
  legal: l(
    'Impressum von Cineradar: Betreiber Wiresoft AG, Anschrift in Baar in der Schweiz sowie Kontakt- und Registerangaben.',
    'Mentions légales de Cineradar : Wiresoft AG, adresse à Baar en Suisse, coordonnées et registre.',
    'Note legali di Cineradar: Wiresoft AG, indirizzo a Baar in Svizzera, contatti e registro.',
    'Aviso legal de Cineradar: Wiresoft AG, dirección en Baar, Suiza, contacto y registro.',
    'Cineradar legal notice: operator Wiresoft AG, address in Baar, Switzerland, contact and registration details.',
  ),
  privacy: l(
    'Datenschutz bei Cineradar: Informationen zu Hosting, Kontaktanfragen, lokalen Merklisten, Länderwahl und deinen Rechten.',
    'Confidentialité sur Cineradar : hébergement, demandes de contact, listes locales, choix du pays et droits.',
    'Privacy su Cineradar: hosting, richieste di contatto, liste locali, scelta del paese e diritti.',
    'Privacidad en Cineradar: alojamiento, consultas, listas locales, elección del país y tus derechos.',
    'Privacy at Cineradar: hosting, contact requests, local watchlists, country preferences and your rights.',
  ),
  credits: l(
    'Datenquellen und Bildnachweise von Cineradar: TMDB und Streaming Availability API von Movie of the Night.',
    'Sources et crédits de Cineradar : TMDB et Streaming Availability API de Movie of the Night.',
    'Fonti e crediti di Cineradar: TMDB e Streaming Availability API di Movie of the Night.',
    'Fuentes y créditos de Cineradar: TMDB y Streaming Availability API de Movie of the Night.',
    'Cineradar data and image credits: TMDB and Streaming Availability API by Movie of the Night.',
  ),
};
export const infoHeadings = {
  privacyIdentify: l(
    'Titelsuche mit Beschreibung und Diktat',
    'Recherche par description et dictée',
    'Ricerca tramite descrizione e dettatura',
    'Búsqueda mediante descripción y dictado',
    'Finding titles by description and dictation',
  ),
  aboutText: l(
    'Was Cineradar macht',
    'Le rôle de Cineradar',
    'Cosa fa Cineradar',
    'Qué hace Cineradar',
    'What Cineradar does',
  ),
  helpIntro: l(
    'So funktioniert die Suche',
    'Utiliser la recherche',
    'Come cercare',
    'Cómo buscar',
    'How search works',
  ),
  dataText: l(
    'Quellen und Aktualität',
    'Sources et actualisation',
    'Fonti e aggiornamenti',
    'Fuentes y actualización',
    'Sources and freshness',
  ),
  newDefinition: l(
    'Was bedeutet „Neu“?',
    'Que signifie « Nouveau » ?',
    'Cosa significa « Novità »?',
    '¿Qué significa « Nuevo »?',
    'What does “New” mean?',
  ),
  leavingDefinition: l(
    'Wenn Angebote auslaufen',
    'Expiration des offres',
    'Scadenza delle offerte',
    'Caducidad de ofertas',
    'When offers expire',
  ),
  freeDefinition: l(
    'Kostenlos ansehen',
    'Regarder gratuitement',
    'Guardare gratis',
    'Ver gratis',
    'Watching for free',
  ),
  addonHelp: l(
    'Abo und Zusatzkanäle unterscheiden',
    'Abonnements et chaînes supplémentaires',
    'Abbonamenti e canali aggiuntivi',
    'Suscripciones y canales adicionales',
    'Subscriptions and add-ons',
  ),
  deviceOnly: l(
    'Deine Merkliste auf diesem Gerät',
    'Votre liste sur cet appareil',
    'La lista su questo dispositivo',
    'Tu lista en este dispositivo',
    'Your watchlist on this device',
  ),
  privacyText: l(
    'Nutzung der Website',
    'Utilisation du site',
    'Utilizzo del sito',
    'Uso del sitio',
    'Using the website',
  ),
  privacyHosting: l(
    'Hosting und technische Daten',
    'Hébergement et données techniques',
    'Hosting e dati tecnici',
    'Alojamiento y datos técnicos',
    'Hosting and technical data',
  ),
  privacyContact: l(
    'Kontaktanfragen',
    'Demandes de contact',
    'Richieste di contatto',
    'Solicitudes de contacto',
    'Contact requests',
  ),
  privacyRights: l(
    'Deine Rechte',
    'Vos droits',
    'I tuoi diritti',
    'Tus derechos',
    'Your rights',
  ),
  contextPrivacy: l(
    'Sprache, Land und lokale Speicherung',
    'Langue, pays et stockage local',
    'Lingua, paese e archiviazione locale',
    'Idioma, país y almacenamiento local',
    'Language, country and local storage',
  ),
  legalIntro: l(
    'Anbieter dieser Website',
    'Éditeur du site',
    'Gestore del sito',
    'Responsable del sitio',
    'Website operator',
  ),
};
