import type { Locale } from '@/i18n/config';
const l = (
  de: string,
  fr: string,
  it: string,
  es: string,
  en: string,
): Record<Locale, string> => ({ de, fr, it, es, en });
export const voiceCopy = {
  title: l('Diktieren', 'Dicter', 'Detta', 'Dictar', 'Dictate'),
  start: l('Diktieren', 'Dicter', 'Detta', 'Dictar', 'Dictate'),
  stop: l('Fertig', 'Terminer', 'Fatto', 'Listo', 'Done'),
  infoLabel: l(
    'Info zur Spracheingabe',
    'Infos sur la dictée',
    'Info sulla dettatura',
    'Información sobre dictado',
    'Voice input information',
  ),
  cancel: l('Abbrechen', 'Annuler', 'Annulla', 'Cancelar', 'Cancel'),
  cancelRequest: l(
    'Anfrage abbrechen',
    'Annuler la demande',
    'Annulla richiesta',
    'Cancelar solicitud',
    'Cancel request',
  ),
  browserInfo: l(
    'Dein Browser kann Audio zur Erkennung an seinen Sprachdienst senden. Cineradar speichert kein Audio; maximal 60 Sekunden pro Diktat.',
    'Votre navigateur peut envoyer l’audio à son service de reconnaissance vocale. Cineradar ne conserve pas l’audio ; 60 secondes maximum par dictée.',
    'Il browser può inviare l’audio al proprio servizio di riconoscimento vocale. Cineradar non conserva l’audio; massimo 60 secondi per dettatura.',
    'Tu navegador puede enviar el audio a su servicio de reconocimiento de voz. Cineradar no guarda el audio; máximo 60 segundos por dictado.',
    'Your browser may send audio to its speech recognition service. Cineradar does not save audio; each dictation lasts up to 60 seconds.',
  ),
  serverInfo: l(
    '„Fertig“ oder das Ende der 60 Sekunden sendet Audio zur Transkription an OpenAI. Vorheriges Abbrechen verwirft die Aufnahme; Cineradar speichert kein Audio.',
    '« Terminer » ou la limite de 60 secondes envoie l’audio à OpenAI pour transcription. Annuler avant l’envoi le supprime ; Cineradar ne conserve pas l’audio.',
    '« Fatto » o il limite di 60 secondi invia l’audio a OpenAI per la trascrizione. Annullare prima dell’invio lo scarta; Cineradar non conserva l’audio.',
    '« Listo » o el límite de 60 segundos envía el audio a OpenAI para transcribirlo. Cancelar antes del envío lo descarta; Cineradar no guarda el audio.',
    '“Done” or the 60-second limit sends audio to OpenAI for transcription. Cancelling before upload discards it; Cineradar does not save audio.',
  ),
  starting: l(
    'Mikrofon startet …',
    'Démarrage du micro…',
    'Avvio del microfono…',
    'Iniciando micrófono…',
    'Starting microphone…',
  ),
  listening: l(
    'Aufnahme läuft …',
    'Enregistrement en cours…',
    'Registrazione in corso…',
    'Grabando…',
    'Recording…',
  ),
  stopping: l(
    'Wird abgeschlossen …',
    'Finalisation…',
    'Completamento…',
    'Terminando…',
    'Finishing…',
  ),
  transcribing: l(
    'Wird transkribiert …',
    'Transcription…',
    'Trascrizione…',
    'Transcribiendo…',
    'Transcribing…',
  ),
  success: l(
    'Text eingefügt.',
    'Texte ajouté.',
    'Testo inserito.',
    'Texto añadido.',
    'Text added.',
  ),
  unsupported: l(
    'Dieser Browser unterstützt kein Diktat.',
    'Ce navigateur ne prend pas en charge la dictée.',
    'Questo browser non supporta la dettatura.',
    'Este navegador no admite dictado.',
    'This browser does not support dictation.',
  ),
  full: l(
    'Zeichenlimit erreicht. Text kürzen.',
    'Limite atteinte. Raccourcissez le texte.',
    'Limite raggiunto. Accorcia il testo.',
    'Límite alcanzado. Acorta el texto.',
    'Character limit reached. Shorten the text.',
  ),
  preview: l(
    'Erkannter Text',
    'Texte reconnu',
    'Testo riconosciuto',
    'Texto reconocido',
    'Recognized text',
  ),
  insecure: l(
    'Diktat benötigt eine sichere Verbindung.',
    'La dictée nécessite une connexion sécurisée.',
    'La dettatura richiede una connessione sicura.',
    'El dictado requiere una conexión segura.',
    'Dictation requires a secure connection.',
  ),
  permission: l(
    'Zugriff blockiert. Mikrofonberechtigung im Browser prüfen.',
    'Accès bloqué. Vérifiez l’autorisation du micro dans le navigateur.',
    'Accesso bloccato. Controlla i permessi del microfono nel browser.',
    'Acceso bloqueado. Revisa el permiso del micrófono en el navegador.',
    'Access blocked. Check microphone permissions in your browser.',
  ),
  microphone: l(
    'Mikrofon nicht verfügbar. Verbindung prüfen.',
    'Micro indisponible. Vérifiez sa connexion.',
    'Microfono non disponibile. Controlla il collegamento.',
    'Micrófono no disponible. Revisa la conexión.',
    'Microphone unavailable. Check its connection.',
  ),
  noSpeech: l(
    'Keine Sprache erkannt. Bitte erneut versuchen.',
    'Aucune parole détectée. Réessayez.',
    'Nessuna voce rilevata. Riprova.',
    'No se detectó voz. Inténtalo de nuevo.',
    'No speech detected. Try again.',
  ),
  language: l(
    'Diktat ist für diese Sprache nicht verfügbar.',
    'La dictée n’est pas disponible pour cette langue.',
    'Dettatura non disponibile per questa lingua.',
    'El dictado no está disponible en este idioma.',
    'Dictation is unavailable for this language.',
  ),
  busy: l(
    'Diktat gerade nicht verfügbar. Später erneut versuchen.',
    'Dictée indisponible. Réessayez plus tard.',
    'Dettatura non disponibile. Riprova più tardi.',
    'Dictado no disponible. Inténtalo más tarde.',
    'Dictation unavailable. Try again later.',
  ),
  failed: l(
    'Diktat fehlgeschlagen. Bitte erneut versuchen.',
    'Échec de la dictée. Réessayez.',
    'Dettatura non riuscita. Riprova.',
    'Error de dictado. Inténtalo de nuevo.',
    'Dictation failed. Try again.',
  ),
  tooLarge: l(
    'Aufnahme zu groß. Bitte kürzer diktieren.',
    'Enregistrement trop volumineux. Dictez moins longtemps.',
    'Registrazione troppo grande. Detta un testo più breve.',
    'Grabación demasiado grande. Prueba un dictado más corto.',
    'Recording too large. Try a shorter dictation.',
  ),
};
