import type { Locale } from '@/i18n/config';
const l = (
  de: string,
  fr: string,
  it: string,
  es: string,
  en: string,
): Record<Locale, string> => ({ de, fr, it, es, en });
export const voiceCopy = {
  title: l(
    'Lieber erzählen?',
    'Vous préférez raconter ?',
    'Preferisci raccontarlo?',
    '¿Prefieres contarlo?',
    'Rather tell us?',
  ),
  start: l(
    'Diktat starten',
    'Commencer la dictée',
    'Inizia a dettare',
    'Empezar a dictar',
    'Start dictation',
  ),
  stop: l(
    'Stopp & Text übernehmen',
    'Arrêter et utiliser le texte',
    'Ferma e usa il testo',
    'Parar y usar el texto',
    'Stop & use text',
  ),
  cancel: l('Abbrechen', 'Annuler', 'Annulla', 'Cancelar', 'Cancel'),
  cancelRequest: l(
    'Anfrage abbrechen',
    'Annuler la demande',
    'Annulla richiesta',
    'Cancelar solicitud',
    'Cancel request',
  ),
  browserInfo: l(
    'Dein Browser wandelt Sprache in Text um und kann Audio an seinen Spracherkennungsdienst senden. Cineradar speichert keine Audiodatei. Maximal 60 Sekunden.',
    'Votre navigateur convertit la parole en texte et peut transmettre le son à son service de reconnaissance vocale. Cineradar ne conserve aucun fichier audio. 60 secondes maximum.',
    'Il browser converte la voce in testo e può inviare l’audio al proprio servizio di riconoscimento vocale. Cineradar non conserva file audio. Massimo 60 secondi.',
    'Tu navegador convierte la voz en texto y puede enviar el audio a su servicio de reconocimiento. Cineradar no guarda archivos de audio. Máximo 60 segundos.',
    'Your browser converts speech to text and may send audio to its speech recognition service. Cineradar does not save an audio file. Up to 60 seconds.',
  ),
  serverInfo: l(
    'Start fragt den Mikrofonzugriff an. Stopp oder das Ende der 60 Sekunden sendet die Aufnahme an OpenAI zur Umwandlung in Text. Abbrechen vor der Übertragung verwirft sie. Cineradar speichert keine Audiodatei.',
    'Démarrer demande l’accès au microphone. Arrêter ou atteindre 60 secondes envoie l’enregistrement à OpenAI pour le transcrire. Annuler avant l’envoi le supprime. Cineradar ne conserve aucun fichier audio.',
    'Avvia richiede l’accesso al microfono. Lo stop o il limite di 60 secondi invia la registrazione a OpenAI per trascriverla. Annullare prima dell’invio la scarta. Cineradar non conserva file audio.',
    'Empezar solicita acceso al micrófono. Parar o llegar a 60 segundos envía la grabación a OpenAI para transcribirla. Cancelar antes del envío la descarta. Cineradar no guarda archivos de audio.',
    'Starting requests microphone access. Stopping or reaching 60 seconds sends the recording to OpenAI for transcription. Cancelling before upload discards it. Cineradar does not save an audio file.',
  ),
  starting: l(
    'Mikrofon wird vorbereitet …',
    'Préparation du microphone…',
    'Preparazione del microfono…',
    'Preparando el micrófono…',
    'Preparing microphone…',
  ),
  listening: l(
    'Ich höre zu. Beschreibe deine Erinnerung.',
    'Je vous écoute. Décrivez votre souvenir.',
    'Ti ascolto. Descrivi il tuo ricordo.',
    'Te escucho. Describe lo que recuerdas.',
    'Listening. Describe what you remember.',
  ),
  stopping: l(
    'Diktat wird abgeschlossen …',
    'Finalisation de la dictée…',
    'Completamento della dettatura…',
    'Terminando el dictado…',
    'Finishing dictation…',
  ),
  transcribing: l(
    'Deine Aufnahme wird in Text umgewandelt …',
    'Transcription de votre enregistrement…',
    'Trascrizione della registrazione…',
    'Transcribiendo tu grabación…',
    'Transcribing your recording…',
  ),
  success: l(
    'Text eingefügt. Du kannst ihn bearbeiten und dann nach dem Titel suchen.',
    'Texte ajouté. Vous pouvez le modifier avant de chercher le titre.',
    'Testo inserito. Puoi modificarlo e poi cercare il titolo.',
    'Texto añadido. Puedes editarlo antes de buscar el título.',
    'Text added. You can edit it before finding the title.',
  ),
  unsupported: l(
    'Spracheingabe ist in diesem Browser nicht verfügbar. Beschreibe deine Erinnerung einfach im Textfeld.',
    'La saisie vocale n’est pas disponible dans ce navigateur. Décrivez simplement votre souvenir dans le champ de texte.',
    'La dettatura non è disponibile in questo browser. Descrivi il ricordo nel campo di testo.',
    'La entrada de voz no está disponible en este navegador. Describe lo que recuerdas en el campo de texto.',
    'Voice input is unavailable in this browser. Describe your memory in the text field.',
  ),
  full: l(
    'Das Textfeld ist voll. Kürze deinen Text, bevor du weiter diktierst.',
    'Le champ est plein. Raccourcissez le texte avant de dicter davantage.',
    'Il campo è pieno. Accorcia il testo prima di continuare a dettare.',
    'El campo está lleno. Acorta el texto antes de seguir dictando.',
    'The text field is full. Shorten it before dictating more.',
  ),
  preview: l(
    'Erkannter Text',
    'Texte reconnu',
    'Testo riconosciuto',
    'Texto reconocido',
    'Recognized text',
  ),
  insecure: l(
    'Spracheingabe benötigt eine sichere Verbindung. Die Texteingabe ist weiterhin möglich.',
    'La saisie vocale nécessite une connexion sécurisée. Vous pouvez toujours saisir du texte.',
    'La dettatura richiede una connessione sicura. Puoi continuare a scrivere.',
    'La entrada de voz requiere una conexión segura. Puedes seguir escribiendo.',
    'Voice input needs a secure connection. You can still type.',
  ),
  permission: l(
    'Mikrofon oder Spracherkennung sind nicht freigegeben. Prüfe die Browserberechtigung oder nutze das Textfeld.',
    'Le microphone ou la reconnaissance vocale ne sont pas autorisés. Vérifiez les permissions du navigateur ou utilisez le champ de texte.',
    'Microfono o riconoscimento vocale non autorizzati. Controlla i permessi del browser o usa il campo di testo.',
    'El micrófono o el reconocimiento no tienen permiso. Revisa los permisos del navegador o usa el campo de texto.',
    'Microphone or speech recognition access is blocked. Check browser permissions or use the text field.',
  ),
  microphone: l(
    'Das Mikrofon ist nicht verfügbar. Prüfe dein Gerät oder gib den Text ein.',
    'Le microphone est indisponible. Vérifiez votre appareil ou saisissez le texte.',
    'Il microfono non è disponibile. Controlla il dispositivo o scrivi il testo.',
    'El micrófono no está disponible. Revisa tu dispositivo o escribe el texto.',
    'The microphone is unavailable. Check your device or type your text.',
  ),
  noSpeech: l(
    'Keine verständliche Sprache erkannt. Versuche es erneut oder tippe deine Erinnerung.',
    'Aucune parole comprise. Réessayez ou saisissez votre souvenir.',
    'Nessuna voce riconosciuta. Riprova o scrivi il tuo ricordo.',
    'No se reconoció voz. Inténtalo de nuevo o escribe lo que recuerdas.',
    'No speech was recognized. Try again or type your memory.',
  ),
  language: l(
    'Die Spracherkennung unterstützt diese Sprache hier nicht. Nutze bitte das Textfeld.',
    'La reconnaissance vocale ne prend pas en charge cette langue ici. Utilisez le champ de texte.',
    'Il riconoscimento vocale non supporta questa lingua. Usa il campo di testo.',
    'El reconocimiento de voz no admite este idioma aquí. Usa el campo de texto.',
    'Speech recognition does not support this language here. Please use the text field.',
  ),
  busy: l(
    'Spracheingabe ist gerade nicht verfügbar. Versuche es später erneut oder nutze das Textfeld.',
    'La saisie vocale est momentanément indisponible. Réessayez plus tard ou utilisez le champ de texte.',
    'La dettatura non è disponibile al momento. Riprova più tardi o usa il campo di testo.',
    'La entrada de voz no está disponible ahora. Inténtalo más tarde o usa el campo de texto.',
    'Voice input is temporarily unavailable. Try later or use the text field.',
  ),
  failed: l(
    'Das Diktat konnte nicht abgeschlossen werden. Dein bisheriger Text bleibt erhalten. Du kannst es erneut versuchen.',
    'La dictée n’a pas pu être terminée. Votre texte est conservé. Vous pouvez réessayer.',
    'Impossibile completare la dettatura. Il testo esistente è conservato. Puoi riprovare.',
    'No se pudo terminar el dictado. El texto anterior se conserva. Puedes volver a intentarlo.',
    'Dictation could not finish. Your existing text is preserved. You can try again.',
  ),
  tooLarge: l(
    'Die Aufnahme ist zu groß. Versuche ein kürzeres Diktat oder nutze das Textfeld.',
    'L’enregistrement est trop volumineux. Essayez une dictée plus courte ou saisissez le texte.',
    'La registrazione è troppo grande. Prova una dettatura più breve o scrivi il testo.',
    'La grabación es demasiado grande. Prueba un dictado más corto o escribe el texto.',
    'The recording is too large. Try a shorter dictation or type your text.',
  ),
};
